### ISSUE TITLE
If PHP_VM is set to hhvm and not in composer.json, composer fails

### ISSUE THREAD

**Issue by chregu** [cloudfoundry/php-buildpack#102]
We want to deploy our app to PHP, as well as HHVM (some part doesn't work with HHVM yet, that's why)

To have not that many moving part, we'd like to only define this in options.json, but currently it needs an adjusted composer.json as well. If we leave out both requirements in composer.json (so no mentioning of php or hhvm), the composer stage fails. It would be nice when it's not defined in composer.json which binary/version you want, it would honour what was in options.json

**Comment by dmikusa-pivotal** [comment]
>To have not that many moving part, we'd like to only define this in options.json

I suspect that Composer, if it's set, will trump options.json, since the Composer extension runs after the default and application specific configuration options are merged together.

>If we leave out both requirements in composer.json (so no mentioning of php or hhvm), the composer stage fails.

Can you attach the output of what you get when this fails?  In this case, I would expect the build pack to use HHVM since you set that in options.json and are not overriding in Composer.

>It would be nice when it's not defined in composer.json which binary/version you want, it would honour what was in options.json

I agree.  I think that should be the default behavior.  Seems like you're seeing different behavior, so we should probably debug more.

**Comment by chregu** [comment]
I will attach the output later, can't push right now and reproduce it.

But it seems quite clear from the code that something is wrong:

In extensions/composer/extension.py in "def configure":
````
            hhvm_version = self.read_version_from_composer('hhvm')
            if hhvm_version:
                self._ctx['PHP_VM'] = 'hhvm'
                self._log.debug('Composer picked HHVM Version [%s]',
                                hhvm_version)
            else:
                # update context with new list of extensions,
                # if composer.json exists
                php_version = self.read_version_from_composer('php')
                self._log.debug('Composer picked PHP Version [%s]',
                                php_version)
                self._ctx['PHP_VERSION'] = self.pick_php_version(php_version)
                self._ctx['PHP_EXTENSIONS'] = utils.unique(exts)
                self._ctx['PHP_VM'] = 'php'
````

which reads to me, that if it can't find hhvm in composer.json it falls back to PHP and picks PHP.

**Comment by chregu** [comment]
Here's the last lines of the log from trying to push such a setup
````
2015-09-23T06:51:16.000+00:00 [STG] ERR 2015-09-23 06:51:16,113 [DEBUG] utils - Processing extension from [/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/php] with method [compile]
2015-09-23T06:51:16.000+00:00 [STG] ERR 2015-09-23 06:51:16,113 [DEBUG] utils - Loading extension from [/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/php]
2015-09-23T06:51:16.000+00:00 [STG] ERR Traceback (most recent call last):
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/scripts/compile.py", line 51, in <module>
2015-09-23T06:51:16.000+00:00 [STG] ERR .from_build_pack('lib/additional_commands')
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/build_pack_utils/builder.py", line 189, in extensions
2015-09-23T06:51:16.000+00:00 [STG] ERR process_extension(path, ctx, 'compile', process, args=[self])
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-09-23T06:51:16.000+00:00 [STG] ERR success(getattr(extn, to_call)(*args))
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/extension_helpers.py", line 48, in extension_helper_wrapper
2015-09-23T06:51:16.000+00:00 [STG] ERR return getattr(inst, 'compile')(install)
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/extension_helpers.py", line 154, in compile
2015-09-23T06:51:16.000+00:00 [STG] ERR self._compile(install)
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/php/extension.py", line 68, in _compile
2015-09-23T06:51:16.000+00:00 [STG] ERR validate_php_version(ctx)
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/compile_helpers.py", line 87, in validate_php_version
2015-09-23T06:51:16.000+00:00 [STG] ERR if ctx['PHP_VERSION'] in ctx['ALL_PHP_VERSIONS']:
2015-09-23T06:51:16.000+00:00 [STG] ERR File "/var/vcap/data/dea_next/admin_buildpacks/3732390d-eed7-4c7f-8e2d-a8c3a5b53045_7b94edcbdd1d17369b8f3bd221bf734ca1dcfb07/lib/build_pack_utils/utils.py", line 151, in __getitem__
2015-09-23T06:51:16.000+00:00 [STG] ERR return self.format(dict.__getitem__(self, key))
2015-09-23T06:51:16.000+00:00 [STG] ERR KeyError: 'ALL_PHP_VERSIONS'
2015-09-23T06:51:16.000+00:00 [STG] OUT Installing PHP
2015-09-23T06:51:16.000+00:00 [STG] OUT Staging failed: Buildpack compilation step failed
````

**Comment by dmikusa-pivotal** [comment]
Yep, you're right.  I didn't test this, but I think it should be doing something like this...

```
            hhvm_version = self.read_version_from_composer('hhvm')
            if hhvm_version:
                self._ctx['PHP_VM'] = 'hhvm'
                self._log.debug('Composer picked HHVM Version [%s]',
                                hhvm_version)
            php_version = self.read_version_from_composer('php')
            if php_version:
                # update context with new list of extensions,
                # if composer.json exists
                self._ctx['PHP_VM'] = 'php'
                self._log.debug('Composer picked PHP Version [%s]',
                                php_version)
                self._ctx['PHP_VERSION'] = self.pick_php_version(php_version)
                self._ctx['PHP_EXTENSIONS'] = utils.unique(exts)
```

The idea would be to look for the PHP version in your composer files and only update the context if it's set.

**Comment by jtarchie** [comment]
@dmikusa-pivotal and @chregu good find!

Would it be easier if we just provided one idiomatic way of defining a PHP/HHVM runtime? That way problems like this don't occur. I would propose `composer.json`, so we could remove responsibility from the `options.json`.

A scenario like this will help remove having to have if/else statements.

Let me know what you think

**Comment by chregu** [comment]
I'm +-0 on this. We deploy the same app to HHVM and PHP and it's easier for us to update options.json instead of composer.json (maybe I'll write another Issue or even PR for that requirement). So I'd still prefer if I could define it in options.json instead of composer.json, but we can live with the other way as well

**Comment by dmikusa-pivotal** [comment]
It probably would be easier, but if we only allow this to be set in Composer then you're effectively forcing people to use Composer if they want HHVM.  I've not had any luck finding numbers on how many people / projects are adopting Composer, but from conversations I know that there are people still not using it so I'd like to see support for both.
