### ISSUE TITLE
Please Update New Relic extension for making it compatible with PHP 7.0

### ISSUE THREAD

**Issue by chregu** [cloudfoundry/php-buildpack#146]
What version of Cloud Foundry are you using?

don't know exactly

What version of the buildpack you are using?

4.3.12

If you were attempting to accomplish a task, what was it you were attempting to do?

Using the New Relic extension on PHP 7 with this buildpack

What did you expect to happen?

New Relic is working

What was the actual behavior?

Doesn't get installed at all, since the provided version is quite old (4.23.3.111), but new relic is at 6.2.1.0 already https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes

I know, I can add that version number to options.json and it's supposed to get downloaded, but it would be nice to have the latest version included in the official buildpack (and also then having it offline available)

{code}
2016-05-17 07:57:17,608 [DEBUG] utils - Processing extension from [/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic] with method [compile]
2016-05-17 07:57:17,608 [DEBUG] utils - Loading extension from [/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic]
2016-05-17 07:57:17,609 [INFO] newrelic - Initializing
2016-05-17 07:57:17,611 [DEBUG] utils - line #58 in /tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_STRIP] = [True]
2016-05-17 07:57:17,612 [DEBUG] utils - line #58 in /tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_DOWNLOAD_URL] = [https://{NEWRELIC_HOST}/php_agent/archive/{NEWRELIC_VERSION}/{NEWRELIC_PACKAGE}]
2016-05-17 07:57:17,613 [DEBUG] utils - line #58 in /tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_PACKAGE] = [newrelic-php5-{NEWRELIC_VERSION}-linux.tar.gz]
2016-05-17 07:57:17,614 [DEBUG] utils - line #58 in /tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_HOST] = [download.newrelic.com]
2016-05-17 07:57:17,615 [DEBUG] utils - line #58 in /tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_VERSION] = [4.23.3.111]
2016-05-17 07:57:17,615 [DEBUG] newrelic - NewRelic service detected.
2016-05-17 07:57:17,616 [DEBUG] newrelic - PHP API [20151012] Arch [x64]
2016-05-17 07:57:17,616 [DEBUG] newrelic - App Name [products-newrelic]
2016-05-17 07:57:17,616 [DEBUG] newrelic - PHP Extension [@{HOME}/newrelic/agent/x64/newrelic-20151012.so]
2016-05-17 07:57:17,616 [DEBUG] newrelic - Log Path [@{HOME}/logs/newrelic-daemon.log]
2016-05-17 07:57:17,616 [DEBUG] newrelic - Daemon [@{HOME}/newrelic/daemon/newrelic-daemon.x64]
2016-05-17 07:57:17,616 [DEBUG] newrelic - Socket [@{HOME}/newrelic/daemon.sock]
2016-05-17 07:57:17,616 [DEBUG] newrelic - Pid File [@{HOME}/newrelic/daemon.pid]
2016-05-17 07:57:17,616 [INFO] newrelic - Installing NewRelic
2016-05-17 07:57:17,617 [DEBUG] cloudfoundry - Installing [NEWRELIC]
2016-05-17 07:57:17,617 [DEBUG] cloudfoundry - Installing binary from manifest [https://download.newrelic.com/php_agent/archive/4.23.3.111/newrelic-php5-4.23.3.111-linux.tar.gz]
/usr/lib/ruby/1.9.1/digest.rb:44:in `initialize': No such file or directory - /tmp/newrelic-php5-4.23.3.111-linux.tar.gz (Errno::ENOENT)
	from /usr/lib/ruby/1.9.1/digest.rb:44:in `open'
	from /usr/lib/ruby/1.9.1/digest.rb:44:in `file'
	from /usr/lib/ruby/1.9.1/digest.rb:29:in `file'
	from /tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/compile-extensions/bin/download_dependency:30:in `<main>'
Traceback (most recent call last):
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/scripts/compile.py", line 50, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/builder.py", line 208, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/extensions/newrelic/extension.py", line 173, in compile
    install.package('NEWRELIC')
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/builder.py", line 184, in package
    self._installer.install_binary(key)
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/cloudfoundry.py", line 206, in install_binary
    strip=strip)
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/cloudfoundry.py", line 176, in _install_binary_from_manifest
    self._dwn.download(url, self._ctx['TMPDIR'])
  File "/tmp/buildpacks/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/downloads.py", line 50, in download
    raise RuntimeError("Could not download dependency: %s" % url)
RuntimeError: Could not download dependency: https://download.newrelic.com/php_agent/archive/4.23.3.111/newrelic-php5-4.23.3.111-linux.tar.gz
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
{code}

Please confirm where necessary:
* [x] I have included a log output 
* [x] My log includes an error message 
* [x]] I have included steps for reproduction

**Comment by Dannyzen** [comment]
Thanks @chregu for putting in the issue. While this is not currently a priority for the team we're open to a pull request.

**Comment by chregu** [comment]
Closed because not gonna do it (needs PR by me), or closed because you did it, but just not committed here?

**Comment by flavorjones** [comment]
@chregu Thanks for asking! 

This work has been done and was committed to the develop branch, and Danny accepted it yesterday. Should be in the next PHP Buildpack release.

**Comment by flavorjones** [comment]
Ah, apologies, there's no clear thread here for me to go off of, so I made assumptions. This work does not appear to have been done.

@Dannyzen can you help @chregu understand whether you'd accept a PR?

**Comment by chregu** [comment]
Ok then, here's the PR #151 for making the new relic extension working again with PHP 7.0

**Comment by Dannyzen** [comment]
@chregu Many thanks for your effort. We'll be sure to get to this as soon as we can for approval.
