### ISSUE TITLE
Staging fails if the app contains a logs/ directory

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/php-buildpack#159]
What version of Cloud Foundry are you using?
222

What version of the buildpack you are using?
v4.3.18

If you were attempting to accomplish a task, what was it you were attempting to do?
Pushing a PHP app with a logs/ directory

What did you expect to happen?
Push to succeed

What was the actual behavior?
Push failed during staging

```
ERR Cloning into 'compile-extensions'...
2016-08-25T09:17:13.54+0900 [STG/0]      OUT Submodule path 'compile-extensions': checked out '8db5f150542cfff06eb12b07e2d4ea1f953f6c0e'
2016-08-25T09:17:13.78+0900 [STG/0]      OUT -------> Buildpack version 4.3.18
2016-08-25T09:17:13.78+0900 [STG/0]      ERR Traceback (most recent call last):
2016-08-25T09:17:13.78+0900 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 37, in <module>
2016-08-25T09:17:13.78+0900 [STG/0]      ERR     .method(setup_log_dir)
2016-08-25T09:17:13.78+0900 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 512, in method
2016-08-25T09:17:13.78+0900 [STG/0]      ERR     execute(self.builder._ctx)
2016-08-25T09:17:13.78+0900 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/compile_helpers.py", line 71, in setup_log_dir
2016-08-25T09:17:13.78+0900 [STG/0]      ERR     os.makedirs(os.path.join(ctx['BUILD_DIR'], 'logs'))
2016-08-25T09:17:13.78+0900 [STG/0]      ERR OSError: [Errno 17] File exists: '/tmp/staged/app/logs'
2016-08-25T09:17:13.78+0900 [STG/0]      ERR   File "/usr/lib/python2.7/os.py", line 157, in makedirs
2016-08-25T09:17:13.78+0900 [STG/0]      ERR     mkdir(name, mode)
2016-08-25T09:17:13.79+0900 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2016-08-25T09:17:13.92+0900 [API/0]      ERR encountered error: App staging failed in the buildpack compile phase
```

**Comment by jchesterpivotal** [comment]
Hi @CAFxX, can you tell us more about what the logs directory is for?

We ask because, as the error shows, the buildpack tries to build its own `logs/` directory in the toplevel (`BUILD_DIR`). This directory is used by the buildpack to write its own logs.

Ideally, you should be emitting application logs directly to STDOUT or STDERR. Otherwise loggregator cannot pick them up for you.

**Comment by CAFxX** [comment]
Application issue, closing
