### ISSUE TITLE
Parallel buildpack compilations fail

### ISSUE THREAD

**Issue by bobbyhubbard** [cloudfoundry/php-buildpack#184]
What version of Cloud Foundry are you using? 1.8

What version of the buildpack you are using? 4.3.24

If you were attempting to accomplish a task, what was it you were attempting to do?
Use Jenkins parallel pipeline to deploy the same app to two spaces at the same time. In our case, we were deploying to dev and qa spaces in the same org. Its possible that a feature branch and a formal dev or qa build could be happening near simulataneous which could also create this issue. Its repeatable 100% of the time if you use the parallel pipeline in jenkins.

What did you expect to happen?
Expected the build to work. :) Not using a parallel build works fine. As soon as we enabled parallel, it broke.

What was the actual behavior?
`ERR OSError: [Errno 17] File exists: '/tmp/app/logs'`

It looks as if the the tmp path is hardcoded to /tmp/app/logs and doesnt use a safe create directory method. IIf both builds end up staging on the same stg server, then obviously there will be a conflict and the directory for one of the builds will already exist. 

Entire log output:
`2016-12-28T16:48:18.51-0600 [STG/0]      OUT Downloading go_buildpack_v1_7_12...
2016-12-28T16:48:18.51-0600 [STG/0]      OUT Downloading java_buildpack_offline...
2016-12-28T16:48:18.51-0600 [STG/0]      OUT Downloading go_buildpack...
2016-12-28T16:48:18.51-0600 [STG/0]      OUT Downloading nodejs_buildpack...
2016-12-28T16:48:18.51-0600 [STG/0]      OUT Downloading ruby_buildpack...
2016-12-28T16:48:18.52-0600 [STG/0]      OUT Downloaded ruby_buildpack
2016-12-28T16:48:18.52-0600 [STG/0]      OUT Downloaded nodejs_buildpack
2016-12-28T16:48:18.52-0600 [STG/0]      OUT Downloading staticfile_buildpack...
2016-12-28T16:48:18.52-0600 [STG/0]      OUT Downloaded go_buildpack
2016-12-28T16:48:18.52-0600 [STG/0]      OUT Downloading php_buildpack_orig...
2016-12-28T16:48:18.52-0600 [STG/0]      OUT Downloaded go_buildpack_v1_7_12
2016-12-28T16:48:18.53-0600 [STG/0]      OUT Downloading python_buildpack...
2016-12-28T16:48:18.53-0600 [STG/0]      OUT Downloaded java_buildpack_offline
2016-12-28T16:48:18.53-0600 [STG/0]      OUT Downloading php_buildpack...
2016-12-28T16:48:18.53-0600 [STG/0]      OUT Downloading binary_buildpack...
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloaded php_buildpack
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloading dotnet-core-buildpack...
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloaded php_buildpack_orig
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloaded staticfile_buildpack
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloaded binary_buildpack
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloaded python_buildpack
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Downloaded dotnet-core-buildpack
2016-12-28T16:48:18.54-0600 [STG/0]      OUT Creating container
2016-12-28T16:48:18.77-0600 [STG/0]      OUT Successfully created container
2016-12-28T16:48:18.77-0600 [STG/0]      OUT Downloading app package...
2016-12-28T16:48:19.48-0600 [STG/0]      OUT Downloaded app package (6M)
2016-12-28T16:48:19.48-0600 [STG/0]      OUT Staging...
2016-12-28T16:48:20.77-0600 [STG/0]      OUT -------> Buildpack version 4.3.24
2016-12-28T16:48:20.77-0600 [STG/0]      ERR Traceback (most recent call last):
2016-12-28T16:48:20.77-0600 [STG/0]      ERR   File "/tmp/buildpacks/c924bf7a9c0f7afb68671e7d287bcbb8/scripts/compile.py", line 37, in <module>
2016-12-28T16:48:20.77-0600 [STG/0]      ERR     .method(setup_log_dir)
2016-12-28T16:48:20.77-0600 [STG/0]      ERR   File "/tmp/buildpacks/c924bf7a9c0f7afb68671e7d287bcbb8/lib/build_pack_utils/builder.py", line 512, in method
2016-12-28T16:48:20.77-0600 [STG/0]      ERR     execute(self.builder._ctx)
2016-12-28T16:48:20.77-0600 [STG/0]      ERR   File "/tmp/buildpacks/c924bf7a9c0f7afb68671e7d287bcbb8/lib/compile_helpers.py", line 71, in setup_log_dir
2016-12-28T16:48:20.77-0600 [STG/0]      ERR     os.makedirs(os.path.join(ctx['BUILD_DIR'], 'logs'))
2016-12-28T16:48:20.77-0600 [STG/0]      ERR   File "/usr/lib/python2.7/os.py", line 157, in makedirs
2016-12-28T16:48:20.77-0600 [STG/0]      ERR     mkdir(name, mode)
2016-12-28T16:48:20.77-0600 [STG/0]      ERR OSError: [Errno 17] File exists: '/tmp/app/logs'
2016-12-28T16:48:20.77-0600 [STG/0]      ERR Failed to compile droplet
2016-12-28T16:48:20.77-0600 [STG/0]      OUT Exit status 223
2016-12-28T16:48:20.78-0600 [STG/0]      ERR Staging failed: Exited with status 223
2016-12-28T16:48:20.79-0600 [STG/0]      OUT Destroying container
2016-12-28T16:48:20.83-0600 [API/1]      ERR Failed to stage application: staging failed
2016-12-28T16:48:21.16-0600 [STG/0]      OUT Successfully destroyed container
`

Please confirm where necessary:
* [X] I have included a log output 
* [X] My log includes an error message 
* [X] I have included steps for reproduction

**Comment by bobbyhubbard** [comment]
Work-around for posterity: do not use parallel pipeline.

**Comment by dmikusa-pivotal** [comment]
I can't comment on Jenkins, but I can confirm that when CF stages your application each app will stage in it's own container and there should be *zero* overlap.

Can you explain more about what's happening when you do this "parallel pipeline" in Jenkins?  Can you also attach logs with the output from staging in both jobs?  It would be interesting to compare and the output you pasted inline is really difficult to read.

As far as the `makedirs` [here](https://github.com/cloudfoundry/php-buildpack/blob/master/lib/compile_helpers.py#L71), it should probably have a check to not attempt to create the directory if it already exists.  In Python 2.7, the `makedirs` method will not fail if intermediate directories in the path already exist, but it will fail if the leaf node exists already.  For example, I believe that this will happen if you push an app that has a top level `logs` directory.  It's easy enough to delete that directory and re-push, but the build pack should probably be more tolerant.

**Comment by sesmith177** [comment]
@bobbyhubbard We agree that the makedirs call should be safe as well. We'll schedule a story to fix this.

As Dan mentioned, it's not clear why `/tmp/app/logs` from two different app stages would interfere -- we'd need more information on what the 'parallel pipeline' is and how it works.

**Comment by sclevine** [comment]
Bug created here: https://www.pivotaltracker.com/story/show/137171925

App filesystems are entirely isolated. It is not possible for logs directories in different apps to interfere with each other in PCF 1.8.

**Comment by bobbyhubbard** [comment]
Totally understand that. We are still baffled why parallel  or simultaneous pushes would cause trouble. Right now, we have no additional details but if we're the only ones experiencing it, I'll assume for now it just something on our setup. :)

**Comment by sesmith177** [comment]
@bobbyhubbard OK, we will close this issue for now. If you find more information / details on your setup that would help us diagnose, please re-open the issue.

**Comment by bobbyhubbard** [comment]
we dug into it a little more and found that via jenkins it would fail, but manually pushing the exact same code from the jenkins filesystem worked. ?? So we let the jenkins process attempt and fail to push the code. We then log into the jenkins box and push the same bits from the jenkins workspace and it works. Clueless. All java, static, and other build pack jobs work fine from the this jenkins build server. Only PHP gives us fits. So, we are punting. We manually patched the buildpack for the safe folder creation and we're no longer blocked. Thanks again.

**Comment by dmikusa-pivotal** [comment]
@bobbyhubbard - Is Jenkins using `cf` to do the push or the CF Java client?  There are somethings in `cf` which are not parallel safe (i.e. if you run two instances of `cf` simultaneously, you could be in for a bad time).  If you're using Jenkins to drive `cf`, you want to make sure that you're using the `CF_HOME` environment variable to point `cf` to a different config location.  This helps with concurrency issues around the `cf` config / state and eliminates a lot of problems.
