### ISSUE TITLE
bug with utf-8 characters in environment variable values

### ISSUE THREAD

**Issue by dbu** [cloudfoundry/php-buildpack#200]
```json
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.test-cloud....",
   "token_endpoint": "https://uaa.test-cloud....",
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.65.0",
   "app_ssh_endpoint": "ssh.test-cloud....:2222",
   "app_ssh_host_key_fingerprint": "c4:87:eb:90:40:6f:4b:1b:47:01:48:30:1d:9e:e0:dd",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.test-cloud..../routing",
   "logging_endpoint": "wss://loggregator.test-cloud.....:443",
   "doppler_logging_endpoint": "wss://doppler.test-cloud.....:443"
}
```
cf version 6.23.0+c7866be-2016-12-22

when we have characters outside of 7-bit ascii in environment variables defined in the manifest.yml, this buildpack explodes during deployment:

```
Staging...
-------> Buildpack version 4.3.18
Installing Nginx
Installing PHP
PHP 7.0.9
Downloaded [file:///tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_php7_php7-7.0.9-linux-x64-1470848044.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_php7_php7-7.0.9-linux-x64-1470848044.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/dependencies/https___buildpacks.cloudfoundry.org_php_binaries_trusty_composer_1.2.0_composer.phar] to [/tmp]
Traceback (most recent call last):
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/scripts/compile.py", line 50, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/lib/build_pack_utils/builder.py", line 208, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/extensions/composer/extension.py", line 414, in compile
    return composer.compile(install)
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/lib/extension_helpers.py", line 154, in compile
    self._compile(install)
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/extensions/composer/extension.py", line 181, in _compile
    self.run()
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/extensions/composer/extension.py", line 316, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/extensions/composer/extension.py", line 358, in run
    env=self._build_composer_environment(),
  File "/tmp/buildpacks/0ebfeda2e75e86b17e6ae0c7340338d4/extensions/composer/extension.py", line 348, in _build_composer_environment
    for (key, val) in env.iteritems()]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
-----> Composer command failed
```

to reproduce, do something like this in manifest.yml:

```yml
env:
  SOME_KEY: "ü"
```

**Comment by sclevine** [comment]
Thanks for the report! Definitely looks like a bug. We'll take a look.

**Comment by dmikusa-pivotal** [comment]
Not able to replicate with latest build pack.

Output from the line indicated in the crash above.

```
2017-03-14 18:00:33,595 [DEBUG] composer - ENV IS: CF_INSTANCE_PORT= (<type 'str'>)
COMPOSER_CACHE_DIR=/tmp/cache/composer (<type 'str'>)
USER=vcap (<type 'str'>)
HOME=/home/vcap (<type 'str'>)
PATH=/usr/local/bin:/usr/bin:/bin:/tmp/app/php/bin (<type 'str'>)
CF_STACK=cflinuxfs2 (<type 'str'>)
LD_LIBRARY_PATH=/tmp/app/php/lib (<type 'str'>)
LANG=en_US.UTF-8 (<type 'str'>)
MEMORY_LIMIT=1024m (<type 'str'>)
VCAP_APPLICATION={"application_id": "8376d601-10c1-4030-865e-f85ec7cc9607", "name": "composer-demo", "limits": {"mem": 1024, "fds": 16384, "disk": 4096}, "space_id": "10180e2b-33b9-44ee-9f8f-da96da17ac1a", "cf_api": "https://api.run.pivotal.io", "application_uris": ["composer-demo.cfapps.io"], "version": "6c008016-2de5-4eb4-a55e-d39aad6975a9", "application_name": "composer-demo", "space_name": "development", "application_version": "6c008016-2de5-4eb4-a55e-d39aad6975a9", "uris": ["composer-demo.cfapps.io"], "users": null} (<type 'str'>)
SHLVL=1 (<type 'str'>)
CF_INSTANCE_IP=10.10.148.92 (<type 'str'>)
CF_INSTANCE_INTERNAL_IP=10.241.138.133 (<type 'str'>)
VCAP_SERVICES={} (<type 'str'>)
PYTHONPATH=/tmp/buildpacks/6048e698a0fbaa73af1a880c0a5b82a5/lib (<type 'str'>)
_=/usr/bin/python (<type 'str'>)
PHPRC=/tmp (<type 'str'>)
BP_DEBUG=true (<type 'str'>)
CF_INSTANCE_PORTS=[] (<type 'str'>)
TEST=ü (<type 'str'>)
CF_INSTANCE_ADDR= (<type 'str'>)
BUILDPACK_PATH=/tmp/buildpacks/6048e698a0fbaa73af1a880c0a5b82a5 (<type 'str'>)
COMPOSER_VENDOR_DIR=/tmp/app/mylibs/vendor (<type 'str'>)
PWD=/home/vcap (<type 'str'>)
COMPOSER_BIN_DIR=/tmp/app/php/bin (<type 'str'>)
Composer version 1.3.2 2017-01-27 18:23:41
...
2017-03-14 18:00:33,751 [DEBUG] composer - ENV IS: CF_INSTANCE_PORT= (<type 'str'>)
COMPOSER_CACHE_DIR=/tmp/cache/composer (<type 'str'>)
USER=vcap (<type 'str'>)
HOME=/home/vcap (<type 'str'>)
PATH=/usr/local/bin:/usr/bin:/bin:/tmp/app/php/bin (<type 'str'>)
LANG=en_US.UTF-8 (<type 'str'>)
MEMORY_LIMIT=1024m (<type 'str'>)
VCAP_APPLICATION={"application_id": "8376d601-10c1-4030-865e-f85ec7cc9607", "name": "composer-demo", "limits": {"mem": 1024, "fds": 16384, "disk": 4096}, "space_id": "10180e2b-33b9-44ee-9f8f-da96da17ac1a", "cf_api": "https://api.run.pivotal.io", "application_uris": ["composer-demo.cfapps.io"], "version": "6c008016-2de5-4eb4-a55e-d39aad6975a9", "application_name": "composer-demo", "space_name": "development", "application_version": "6c008016-2de5-4eb4-a55e-d39aad6975a9", "uris": ["composer-demo.cfapps.io"], "users": null} (<type 'str'>)
SHLVL=1 (<type 'str'>)
CF_INSTANCE_IP=10.10.148.92 (<type 'str'>)
CF_INSTANCE_INTERNAL_IP=10.241.138.133 (<type 'str'>)
PYTHONPATH=/tmp/buildpacks/6048e698a0fbaa73af1a880c0a5b82a5/lib (<type 'str'>)
TEST=ü (<type 'str'>)
_=/usr/bin/python (<type 'str'>)
COMPOSER_VENDOR_DIR=/tmp/app/mylibs/vendor (<type 'str'>)
PHPRC=/tmp (<type 'str'>)
BP_DEBUG=true (<type 'str'>)
COMPOSER_BIN_DIR=/tmp/app/php/bin (<type 'str'>)
CF_STACK=cflinuxfs2 (<type 'str'>)
LD_LIBRARY_PATH=/tmp/app/php/lib (<type 'str'>)
VCAP_SERVICES={} (<type 'str'>)
CF_INSTANCE_PORTS=[] (<type 'str'>)
CF_INSTANCE_ADDR= (<type 'str'>)
BUILDPACK_PATH=/tmp/buildpacks/6048e698a0fbaa73af1a880c0a5b82a5 (<type 'str'>)
PWD=/home/vcap (<type 'str'>)
```

Note the `TEST` env variable that has a `ü` as the value.

Is that the exact character that you're using?  Also, can you try with the latest build pack and see if it still happens?

**Comment by sclevine** [comment]
@dbu are you still experiencing this issue with the latest version of the buildpack?

**Comment by sclevine** [comment]
Closing due to inactivity.
