### ISSUE TITLE
Staging failling to Japanese char. in Env. variable

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/php-buildpack#225]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf api version 2.75.00
cf version 6.27

What version of the buildpack you are using?
4.3.38

If you were attempting to accomplish a task, what was it you were attempting to do?
Try to push /  stage my app with japanese char. in the env. variable

```bash
cf set-env CLUSTERS_INFO ' {"dev01":{"env":"開発環境","use":"YJ向け","center":"新白河(ssk)"},"sandbox":{"env":"検証環境","use":"","center":""}}'
```

```
cf push myphpapp
```

```
Downloading php_buildpack...
Downloaded php_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (21.4M)
Downloading build artifacts cache...
Downloaded build artifacts cache (325B)
Staging...
-------> Buildpack version 4.3.38
HTTPD 2.4.27
Installing HTTPD
Downloaded [file:///tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.27-linux-x64-ebe06494.tgz] to [/tmp]
WARNING: A version of PHP has been specified in both `composer.json` and `./bp-config/options.json`.
Installing PHP
WARNING: The version defined in `composer.json` will be used.
Warning: PHP_EXTENSIONS in options.json is deprecated. See: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html
PHP 5.6.31
Downloaded [file:///tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.31-linux-x64-c495c457.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.31-linux-x64-c495c457.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer-1.4.2-3a1d1c6c.phar] to [/tmp]
-----> Composer command failed
Traceback (most recent call last):
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/scripts/compile.py", line 55, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/lib/build_pack_utils/builder.py", line 209, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/extensions/composer/extension.py", line 429, in compile
    return composer.compile(install)
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/lib/extension_helpers.py", line 154, in compile
    self._compile(install)
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/extensions/composer/extension.py", line 196, in _compile
    self.run()
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/extensions/composer/extension.py", line 331, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/extensions/composer/extension.py", line 373, in run
    env=self._build_composer_environment(),
  File "/tmp/buildpacks/e4673578a6ae2a7df61aae2f4e5a713d/extensions/composer/extension.py", line 363, in _build_composer_environment
    for (key, val) in env.iteritems()]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 31: ordinal not in range(128)
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
```

What did you expect to happen?
Stage and run successfully

What was the actual behavior?
Staging failed

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [X ] I have included steps for reproduction

**Comment by keaty** [comment]
Hi @shinji62, we're having difficulty recreating this issue. Is it possible to provide an example app that outputs this error on push? Thanks.

**Comment by shinji62** [comment]
@keaty You need composer file.

like

composer.json
```
{
    "name": "etourg/test",
    "authors": [
        {
            "name": "Etourneau Gwenn",
            "email": "gwenn.etourneau@gmail.com"
        }
    ],
    "require": {
    "guzzlehttp/guzzle":"3.x",
    }
}
```
and small php app `index.php`
```
<?php
echo phpinfo();

```
Then push and start using this env. variable.
```bash
cf push gwenn-test --no-start
cf set-env gwenn-test CLUSTERS_INFO '{"dev01":{"env":"開発環境","use":"YJ向け","center":"新白河(ssk)"},"sandbox":{"env":" 検証環境","use":"","center":""}}'
```

**Comment by dgodd** [comment]
hi @shinji62 

I just pushed https://github.com/dgodd/gwenn-test as a clean app to my CF cluster and sadly it worked. Could you please try pushing it yourself, and making any PRs neccessary to make it fail.

A different suggestion, was that it might be something related to ENV, specifically LANG, I have LANG set to 'en_US.UTF-8' on both my machine and the cluster I push to. Is yours different?

I include all of the env vars from the running app (I excluded the values from some, specifically those lines missing '='), if you see anything different please tell me

```
CF_INSTANCE_ADDR
TERM=screen
VCAP_APP_PORT=8080
USER=vcap
LS_COLORS
CF_INSTANCE_INTERNAL_IP=10.246.141.143
VCAP_APPLICATION
CF_INSTANCE_GUID=0696eab6-8880-4335-55d7-b84b
PATH=/bin:/usr/bin
PWD=/home/vcap
LANG=en_US.UTF-8
CF_INSTANCE_PORT=61118
CF_INSTANCE_IP=10.10.149.132
VCAP_SERVICES={}
CF_INSTANCE_INDEX=0
SHLVL=1
HOME=/home/vcap
CF_INSTANCE_PORTS=[{"external":61118,"internal":8080},{"external":61119,"internal":2222}]
LESSOPEN=| /bin/lesspipe %s
INSTANCE_INDEX=0
CLUSTERS_INFO={"dev01":{"env":"開発環境","use":"YJ向け","center":"新白河(ssk)"},"sandbox":{"env":" 検証環境","use":"","center":""}}
PORT=8080
VCAP_APP_HOST=0.0.0.0
INSTANCE_GUID=0696eab6-8880-4335-55d7-b84b
LESSCLOSE=/bin/lesspipe %s %s
MEMORY_LIMIT=1024m
_=/usr/bin/env
```

**Comment by dmikusa-pivotal** [comment]
+1 works for me on PWS too

```
Moonraker:composer-test dmikusa$ cf push dmikusa-test --no-start
Creating app dmikusa-test in org dmikusa / space development as dmikusa@gopivotal.com...
OK

Creating route dmikusa-test.cfapps.io...
OK

Binding dmikusa-test.cfapps.io to dmikusa-test...
OK

Uploading dmikusa-test...
Uploading app files from: /Users/dmikusa/Downloads/composer-test
Uploading 412B, 2 files
Done uploading
OK

Moonraker:composer-test dmikusa$ cf set-env dmikusa-test CLUSTERS_INFO '{"dev01":{"env":"開発環境","use":"YJ向け","center":"新白河(ssk)"},"sandbox":{"env":" 検証環境","use":"","center":""}}'
Setting env variable 'CLUSTERS_INFO' to '{"dev01":{"env":"開発環境","use":"YJ向け","center":"新白河(ssk)"},"sandbox":{"env":" 検証環境","use":"","center":""}}' for app dmikusa-test in org dmikusa / space development as dmikusa@gopivotal.com...
OK
TIP: Use 'cf restage dmikusa-test' to ensure your env variable changes take effect

Moonraker:composer-test dmikusa$ cf start dmikusa-test
Starting app dmikusa-test in org dmikusa / space development as dmikusa@gopivotal.com...

Staging app and tracing logs...
   Downloading binary_buildpack...
   Downloading java_buildpack...
   Downloading nodejs_buildpack...
   Downloading staticfile_buildpack...
   Downloading ruby_buildpack...
   Downloaded nodejs_buildpack
   Downloaded java_buildpack
   Downloading php_buildpack...
   Downloading go_buildpack...
   Downloaded binary_buildpack
   Downloading python_buildpack...
   Downloaded staticfile_buildpack
   Downloading dotnet_core_buildpack_beta...
   Downloaded ruby_buildpack
   Downloading dotnet_core_buildpack...
   Downloaded python_buildpack
   Downloaded php_buildpack
   Downloaded go_buildpack
   Downloaded dotnet_core_buildpack
   Downloaded dotnet_core_buildpack_beta
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (412B)
   -------> Buildpack version 4.3.41
   Installing HTTPD
   Installing PHP
   HTTPD 2.4.27
   Downloaded [file:///tmp/buildpacks/ed483e37c1b0d5b580b4e156cb8d935c/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.27-linux-x64-ebe06494.tgz] to [/tmp]
   PHP 5.6.31
   Downloaded [file:///tmp/buildpacks/ed483e37c1b0d5b580b4e156cb8d935c/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.31-linux-x64-2ed515dd.tgz] to [/tmp]
   Downloaded [file:///tmp/buildpacks/ed483e37c1b0d5b580b4e156cb8d935c/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.31-linux-x64-2ed515dd.tgz] to [/tmp]
   Downloaded [file:///tmp/buildpacks/ed483e37c1b0d5b580b4e156cb8d935c/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer-1.5.1-43e330d8.phar] to [/tmp]
   Updating dependencies
   PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
   Loading composer repositories with package information
   Package operations: 2 installs, 0 updates, 0 removals
     - Installing symfony/event-dispatcher (v3.3.8): Downloading (100%)
     - Installing guzzlehttp/guzzle (v3.8.1): Downloading (100%)
   Writing lock file
   Generating autoload files
   Finished: [2017-09-11 12:20:06.297851]
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading build artifacts cache...
   Uploading droplet...
   Uploaded build artifacts cache (9.3M)
   Uploaded droplet (58.2M)

Waiting for app to start...

name:              dmikusa-test
requested state:   started
instances:         1/1
usage:             1G x 1 instances
routes:            dmikusa-test.cfapps.io
last uploaded:     Mon 11 Sep 08:19:15 EDT 2017
stack:             cflinuxfs2
buildpack:         php 4.3.41
start command:     $HOME/.bp/bin/start

     state     since                  cpu    memory    disk      details
#0   running   2017-09-11T12:20:31Z   0.0%   0 of 1G   0 of 1G
```

**Comment by dmikusa-pivotal** [comment]
LANG is also set to utf-8 for me.

```
Moonraker:composer-test dmikusa$ env | grep LANG
LANG=en_US.UTF-8
Moonraker:composer-test dmikusa$ cf ssh dmikusa-test
vcap@2ec1a72e-4382-4925-6244-2980:~$ env | grep LANG
LANG=en_US.UTF-8
```

**Comment by shinji62** [comment]
Ok I now can you add this options.json in your app ??
.bp-config/options.json
```
{
    "COMPOSER_VENDOR_DIR": "vendor",
    "PHP_EXTENSIONS": ["bz2", "zlib", "curl", "mcrypt","pdo"]
}
```

**Comment by dgodd** [comment]
Thanks @shinji62. That exposed the bug, we'll start fixing it.

**Comment by sclevine** [comment]
This was fixed in the latest release.
