### ISSUE TITLE
Failure trying to deploy cf-ex-phppgadmin

### ISSUE THREAD

**Issue by chefhoobajoob** [cloudfoundry/php-buildpack#241]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

curl:
```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.bp-cf.<domain>",
   "token_endpoint": "https://uaa.bp-cf.<domain>",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.98.0",
   "app_ssh_endpoint": "ssh.bp-cf.<domain>:2222",
   "app_ssh_host_key_fingerprint": "0a:08:87:b5:45:46:e0:60:fd:0f:c2:d4:e8:2d:57:e8",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.bp-cf.<domain>:443",
   "routing_endpoint": "https://api.bp-cf.<domain>/routing"
}
```

version:
```
cf.exe version 6.32.0+0191c33d9.2017-09-26
```

What version of the buildpack you are using?
4.3.42

If you were attempting to accomplish a task, what was it you were attempting to do?
To push the [cf-ex-phppgadmin](https://github.com/cloudfoundry-samples/cf-ex-phppgadmin) example php app, using the command: `cf push`, as described in that project's `README.md`.

What did you expect to happen?
I expected the app to successfully deploy

What was the actual behavior?
cf push fails with the following error:

```
-------> Buildpack version 4.3.42
Installing HTTPD
HTTPD 2.4.27
Traceback (most recent call last):
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/scripts/compile.py", line 55, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/build_pack_utils/builder.py", line 209, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/httpd/extension.py", line 45, in compile
    .package('HTTPD')
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/build_pack_utils/builder.py", line 185, in package
    self._installer.install_binary(key)
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/build_pack_utils/cloudfoundry.py", line 214, in install_bin
ary
    strip=strip)
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/build_pack_utils/cloudfoundry.py", line 190, in _install_bi
nary_from_manifest
    self._dwn.download(url, self._ctx['TMPDIR'])
  File "/tmp/buildpacks/b9d2a80e3f1bbb4448d9b085812e89e2/lib/build_pack_utils/downloads.py", line 40, in download
    raise RuntimeError("MD5 of downloaded dependency does not match expected value")
RuntimeError: MD5 of downloaded dependency does not match expected value
Failed to compile droplet: Failed to run finalize script: exit status 1
Exit status 223
Stopping instance 7371b458-ee65-4ce2-a7c9-1dbc562ee444
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed
```

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
@chefhoobajoob Are you using a modified version of the buildpack that downloads different dependencies?

**Comment by sclevine** [comment]
Closing due to inactivity.
