### ISSUE TITLE
 PHP gets downloaded twice?

### ISSUE THREAD

**Issue by ocean90** [cloudfoundry/php-buildpack#271]
**What version of Cloud Foundry and CF CLI are you using?**

2.114.0 and 6.37.0+a40009753.2018-05-25

**What version of the buildpack you are using?**

4.3.57

**What did you expect to happen?**

During `cf push` only one `Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.19-linux-x64-8c6ec194.tgz] to [/tmp]` message should be displayed.

**What was the actual behavior?**

Based on the message, PHP gets downloaded twice?

```
  Installing PHP
   PHP 7.1.17
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.17-linux-x64-5306e01c.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.17-linux-x64-5306e01c.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/composer/composer-1.6.5-67bebe9d.phar] to [/tmp]
```

Here's the relevant debug log:

<details>

```
2018-07-04 20:07:32,984 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/nginx]
Installing Nginx
2018-07-04 20:07:32,985 [DEBUG] utils - line #37 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/nginx/extension.py, "compile" is setting [PHP_FPM_LISTEN] = [{TMPDIR}/php-fpm.socket]
2018-07-04 20:07:32,985 [DEBUG] cloudfoundry - Installing [NGINX]
2018-07-04 20:07:32,985 [DEBUG] cloudfoundry - Installing binary from manifest [/nginx/1.15.0/nginx-1.15.0.tar.gz]
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/nginx-static/nginx-1.15.0-linux-x64-64919fa9.tgz] to [/tmp]
2018-07-04 20:07:33,326 [INFO] zips - Extracting [/tmp/nginx-1.15.0.tar.gz] into [/tmp/app/nginx]
2018-07-04 20:07:33,393 [DEBUG] utils - line #185 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/build_pack_utils/builder.py, "package" is setting [NGINX_INSTALL_PATH] = [/tmp/app/nginx]
2018-07-04 20:07:33,394 [INFO] builder - Installed [NGINX] to [/tmp/app/nginx]
2018-07-04 20:07:33,394 [DEBUG] cloudfoundry - Install file [defaults/config/nginx] from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c]
2018-07-04 20:07:33,394 [DEBUG] cloudfoundry - Copying [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/defaults/config/nginx] to [/tmp/app/nginx/conf]
2018-07-04 20:07:33,396 [DEBUG] cloudfoundry - Install file [.bp-config/nginx] from [/tmp/app]
2018-07-04 20:07:33,396 [DEBUG] cloudfoundry - Copying [/tmp/app/.bp-config/nginx] to [/tmp/app/nginx/conf]
2018-07-04 20:07:33,397 [INFO] utils - Rewriting configuration under [/tmp/app/nginx/conf]
2018-07-04 20:07:33,398 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/fastcgi_params]
2018-07-04 20:07:33,398 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/http-defaults.conf]
2018-07-04 20:07:33,398 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/http-logging.conf]
2018-07-04 20:07:33,399 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/http-php.conf]
2018-07-04 20:07:33,399 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/mime.types]
2018-07-04 20:07:33,399 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/nginx-defaults.conf]
2018-07-04 20:07:33,399 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/nginx-workers.conf]
2018-07-04 20:07:33,400 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/nginx.conf]
2018-07-04 20:07:33,400 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/server-defaults.conf]
2018-07-04 20:07:33,400 [DEBUG] utils - Rewriting [/tmp/app/nginx/conf/server-locations.conf]
NGINX 1.15.0
2018-07-04 20:07:33,401 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/php] with method [compile]
2018-07-04 20:07:33,401 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/php]
Installing PHP
2018-07-04 20:07:33,401 [DEBUG] helpers - App selected PHP [7.1.19]
2018-07-04 20:07:33,401 [DEBUG] cloudfoundry - Installing [PHP]
PHP 7.1.19
2018-07-04 20:07:33,401 [DEBUG] cloudfoundry - Installing binary from manifest [/php/7.1.19/php-7.1.19.tar.gz]
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.19-linux-x64-8c6ec194.tgz] to [/tmp]
2018-07-04 20:07:35,155 [INFO] zips - Extracting [/tmp/php-7.1.19.tar.gz] into [/tmp/app/php]
2018-07-04 20:07:36,773 [DEBUG] utils - line #185 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/build_pack_utils/builder.py, "package" is setting [PHP_INSTALL_PATH] = [/tmp/app/php]
2018-07-04 20:07:36,774 [INFO] builder - Installed [PHP] to [/tmp/app/php]
2018-07-04 20:07:36,798 [DEBUG] utils - line #148 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/compile_helpers.py, "validate_php_extensions" is setting [PHP_EXTENSIONS] = [[u'bz2', u'zlib', u'curl', u'mcrypt', 'openssl', 'mbstring']]
2018-07-04 20:07:36,798 [DEBUG] helpers - Converting PHP extensions
2018-07-04 20:07:36,799 [DEBUG] utils - line #186 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/compile_helpers.py, "convert_php_extensions" is setting [PHP_EXTENSIONS] = [extension=bz2.so
extension=zlib.so
extension=curl.so
extension=mcrypt.so
extension=openssl.so
extension=mbstring.so]
2018-07-04 20:07:36,799 [DEBUG] utils - line #190 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/compile_helpers.py, "convert_php_extensions" is setting [ZEND_EXTENSIONS] = []
2018-07-04 20:07:36,799 [DEBUG] utils - line #175 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/compile_helpers.py, "include_fpm_d_confs" is setting [PHP_FPM_CONF_INCLUDE] = []
2018-07-04 20:07:36,800 [DEBUG] cloudfoundry - Install file [defaults/config/php/7.1.x] from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c]
2018-07-04 20:07:36,800 [DEBUG] cloudfoundry - Copying [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/defaults/config/php/7.1.x] to [/tmp/app/php/etc]
2018-07-04 20:07:36,801 [DEBUG] cloudfoundry - Install file [.bp-config/php] from [/tmp/app]
2018-07-04 20:07:36,801 [DEBUG] cloudfoundry - Copying [/tmp/app/.bp-config/php] to [/tmp/app/php/etc]
2018-07-04 20:07:36,802 [INFO] utils - Rewriting configuration under [/tmp/app/php/etc]
2018-07-04 20:07:36,802 [DEBUG] utils - Rewriting [/tmp/app/php/etc/pear.conf]
2018-07-04 20:07:36,803 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php-fpm.conf]
2018-07-04 20:07:36,804 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini]
2018-07-04 20:07:36,806 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php-fpm.d/www.conf.default]
2018-07-04 20:07:36,806 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/custom.ini]
2018-07-04 20:07:36,807 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/exif.ini]
2018-07-04 20:07:36,807 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/fileinfo.ini]
2018-07-04 20:07:36,807 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/imagick.ini]
2018-07-04 20:07:36,807 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/mysqli.ini]
2018-07-04 20:07:36,807 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/redis.ini]
2018-07-04 20:07:36,808 [DEBUG] utils - Rewriting [/tmp/app/php/etc/php.ini.d/zip.ini]
2018-07-04 20:07:36,808 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/appdynamics] with method [compile]
2018-07-04 20:07:36,808 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/appdynamics]
2018-07-04 20:07:36,808 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/dynatrace] with method [compile]
2018-07-04 20:07:36,808 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/dynatrace]
2018-07-04 20:07:36,808 [INFO] dynatrace - Initializing
2018-07-04 20:07:36,808 [INFO] dynatrace - Loading service info
2018-07-04 20:07:36,808 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/geoip] with method [compile]
2018-07-04 20:07:36,808 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/geoip]
2018-07-04 20:07:36,808 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic] with method [compile]
2018-07-04 20:07:36,809 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic]
2018-07-04 20:07:36,809 [INFO] newrelic - Initializing
DEBUG: default_version_for newrelic is 8.1.0.209
2018-07-04 20:07:36,883 [INFO] newrelic - Using NewRelic default version: 8.1.0.209
2018-07-04 20:07:36,884 [DEBUG] utils - line #66 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic/extension.py, "_set_default_version" is setting [NEWRELIC_VERSION] = [8.1.0.209]
2018-07-04 20:07:36,884 [DEBUG] utils - line #71 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_DOWNLOAD_URL] = [https://{NEWRELIC_HOST}/php_agent/archive/{NEWRELIC_VERSION}/{NEWRELIC_PACKAGE}]
2018-07-04 20:07:36,885 [DEBUG] utils - line #71 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_PACKAGE] = [newrelic-php5-{NEWRELIC_VERSION}-linux.tar.gz]
2018-07-04 20:07:36,885 [DEBUG] utils - line #71 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_HOST] = [download.newrelic.com]
2018-07-04 20:07:36,885 [DEBUG] utils - line #71 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic/extension.py, "_merge_defaults" is setting [NEWRELIC_STRIP] = [True]
2018-07-04 20:07:36,885 [INFO] newrelic - NewRelic services not detected.
2018-07-04 20:07:36,886 [DEBUG] newrelic - PHP API [20160303] Arch [x64]
2018-07-04 20:07:36,886 [DEBUG] newrelic - App Name [redacted]
2018-07-04 20:07:36,886 [DEBUG] utils - line #101 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/newrelic/extension.py, "_load_newrelic_info" is setting [NEWRELIC_LICENSE] = [None]
2018-07-04 20:07:36,887 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm] with method [compile]
2018-07-04 20:07:36,887 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm]
2018-07-04 20:07:36,887 [INFO] CAAPM - Initializing
2018-07-04 20:07:36,887 [INFO] CAAPM - Loading defaults info
2018-07-04 20:07:36,887 [DEBUG] utils - line #55 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm/extension.py, "_merge_defaults" is setting [CAAPM_DOWNLOAD_URL] = [https://{CA_APM_DOWNLOAD_HOST}/{CA_APM_PHP_PACKAGE}]
2018-07-04 20:07:36,888 [DEBUG] utils - line #55 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm/extension.py, "_merge_defaults" is setting [CA_APM_DOWNLOAD_HOST] = [ca.bintray.com/apm-agents]
2018-07-04 20:07:36,888 [DEBUG] utils - line #55 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm/extension.py, "_merge_defaults" is setting [CA_APM_DOWNLOAD_VERSION] = [10.7.0]
2018-07-04 20:07:36,888 [DEBUG] utils - line #55 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm/extension.py, "_merge_defaults" is setting [CA_APM_PHP_PACKAGE] = [CA-APM-PHPAgent-{CA_APM_DOWNLOAD_VERSION}_linux.tar.gz]
2018-07-04 20:07:36,888 [INFO] CAAPM - Loading service info to find CA APM Service
2018-07-04 20:07:36,888 [INFO] CAAPM - Searching for CA APM service in user-provided services
2018-07-04 20:07:36,888 [ERROR] CAAPM - Error installing CA APM PHP Agent.
Traceback (most recent call last):
  File "/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm/extension.py", line 46, in __init__
    self._load_service_info()
  File "/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/caapm/extension.py", line 80, in _load_service_info
    for user_service in user_services:
TypeError: 'NoneType' object is not iterable
2018-07-04 20:07:36,889 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/sessions] with method [compile]
2018-07-04 20:07:36,889 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/sessions]
2018-07-04 20:07:36,889 [DEBUG] utils - Processing extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/composer] with method [compile]
2018-07-04 20:07:36,889 [DEBUG] utils - Loading extension from [/tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/extensions/composer]
DEBUG: default_version_for composer is 1.6.5
2018-07-04 20:07:36,967 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_HOME] = [{CACHE_DIR}/composer]
2018-07-04 20:07:36,968 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_DOWNLOAD_URL] = [/composer/{COMPOSER_VERSION}/{COMPOSER_PACKAGE}]
2018-07-04 20:07:36,968 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_CACHE_DIR] = [{COMPOSER_HOME}/cache]
2018-07-04 20:07:36,969 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_VENDOR_DIR] = [{BUILD_DIR}/{LIBDIR}/vendor]
2018-07-04 20:07:36,970 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_PACKAGE] = [composer.phar]
2018-07-04 20:07:36,970 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_BIN_DIR] = [{BUILD_DIR}/php/bin]
2018-07-04 20:07:36,970 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_INSTALL_GLOBAL] = [[]]
2018-07-04 20:07:36,971 [DEBUG] utils - line #54 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/extension_helpers.py, "_merge_defaults" is setting [COMPOSER_VERSION] = [1.6.5]
2018-07-04 20:07:36,971 [DEBUG] builder - Copying files from [/tmp/app/php/etc] to [/tmp]
2018-07-04 20:07:36,971 [DEBUG] builder - Copying [/tmp/app/php/etc/php.ini] to [/tmp/php.ini]
2018-07-04 20:07:36,973 [INFO] utils - Rewriting configuration file [/tmp/php.ini]
2018-07-04 20:07:36,975 [DEBUG] cloudfoundry - Using python downloader.
2018-07-04 20:07:36,975 [DEBUG] downloads - Loaded proxy handlers [{}]
2018-07-04 20:07:36,975 [DEBUG] cloudfoundry - Installing [PHP]
2018-07-04 20:07:36,975 [DEBUG] cloudfoundry - Installing binary from manifest [/php/7.1.19/php-7.1.19.tar.gz]
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.19-linux-x64-8c6ec194.tgz] to [/tmp]
2018-07-04 20:07:37,935 [INFO] zips - Extracting [/tmp/php-7.1.19.tar.gz] into [/tmp/app/php]
2018-07-04 20:07:39,491 [DEBUG] utils - line #185 in /tmp/buildpackdownloads/74d433cff05812cefca3ab88ebfaa47c/lib/build_pack_utils/builder.py, "package" is setting [PHP_INSTALL_PATH] = [/tmp/app/php]
2018-07-04 20:07:39,491 [INFO] builder - Installed [PHP] to [/tmp/app/php]
```

</details>

**Comment by dmikusa-pivotal** [comment]
Can you include a demo application to replicate this behavior?  I don't see this behavior with my demo apps.  

The buildpack extension that installs PHP should only get called once and only install PHP once.  While I don't think it will hurt anything, maybe just waste a small amount of time, it does look like it's installing PHP twice.  I would like to try and replicate this to understand how it's happening.

Thanks

**Comment by astrieanna** [comment]
@ocean90 ^^ are you able to provide a demo app?

**Comment by sclevine** [comment]
Closing due to inactivity.
