### ISSUE TITLE
Unable to deploy cloudfoundry-community/phpmyadmin-cf application

### ISSUE THREAD

**Issue by vlvanchin** [cloudfoundry/php-buildpack#276]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
please find the snippet for the above curl: 

   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.94.0"

What version of the buildpack you are using?
In my push command the build pack is passed by -b option as follows
$ cf push -b https://github.com/cloudfoundry/php-buildpack.git

If you were attempting to accomplish a task, what was it you were attempting to do?
I am trying the following:

1.     I downloaded the  https://github.com/cloudfoundry-community/phpmyadmin-cf/archive/cf-ready.zip from the repository to my local system
2.     I extracted the zip to a temp folder and changed directory to it.
3.     Ran the following : 
        $ cf push -b https://github.com/cloudfoundry/php-buildpack.git

What did you expect to happen?
I would expect to have phpmyadmin web application being deployed to cloud.

What was the actual behavior?
Getting Error:
```
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension.
-----> Composer command failed
Traceback (most recent call last):
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/scripts/compile.py", line 59, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/builder.py", line 209, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 443, in compile
    return composer.compile(install)
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/extension_helpers.py", line 154, in compile
    self._compile(install)
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 196, in _compile
    self.run()
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 343, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 389, in run
    shell=True)
  File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/runner.py", line 109, in stream_output
    raise CalledProcessError(retcode, cmd)
build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7ff93c8bc9c0>' returned non-zero exit status 2
Failed to compile droplet: Failed to run finalize script: exit status 1
Exit status 223
Cell 03078fb0-f90b-401c-afde-e0035ee3a0a0 stopping instance 34c365d2-786a-4f53-accb-a0ebe0edcfda
Cell 03078fb0-f90b-401c-afde-e0035ee3a0a0 destroying container for instance 34c365d2-786a-4f53-accb-a0ebe0edcfda
Cell 03078fb0-f90b-401c-afde-e0035ee3a0a0 successfully destroyed container for instance 34c365d2-786a-4f53-accb-a0ebe0edcfda
```
Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

Please help to guide me to get this issue fixed.

**Comment by dmikusa-pivotal** [comment]
The reason this happens is because the buildpack installs PHP 7.2 by default, and 7.2 no longer has the mcrypt extension. It's been removed.  Either force an older version of PHP, which still has mcrypt or remote the reference to it from your composer.json file.

Alternatively, you can use this repo: https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin

It should work out-of-the-box with the latest PHP 7.2 & latest PHP buildpack.

**Comment by vlvanchin** [comment]
Dear @dmikusa-pivotal 
Thank you so much for the reply. I have the alternative solution done and it works well.  👍

**Comment by dmikusa-pivotal** [comment]
Fantastic! Sounds like we can close this out.

**Comment by vlvanchin** [comment]
Dear Team,

I am using this repo: https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin web app to be pushed to our CF cloud. But i am getting this error when i do the git push.

--
2018-09-06T13:19:40.63+0800 [STG/0] OUT -------> Buildpack version 4.3.59
2018-09-06T13:19:41.54+0800 [STG/0] OUT Installing HTTPD
2018-09-06T13:19:41.54+0800 [STG/0] OUT HTTPD 2.4.34
2018-09-06T13:19:41.67+0800 [STG/0] OUT Downloaded [file:///tmp/buildpacks/259d00c2a434b633814fb18cddc73430/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.34-linux-x64-cflinuxfs2-a84dc5b4.tgz] to [/tmp]
2018-09-06T13:19:41.91+0800 [STG/0] OUT Installing PHP
2018-09-06T13:19:41.91+0800 [STG/0] OUT PHP 7.2.8
2018-09-06T13:19:42.39+0800 [STG/0] OUT Downloaded [file:///tmp/buildpacks/259d00c2a434b633814fb18cddc73430/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php7-7.2.8-linux-x64-cflinuxfs2-570d0ad4.tgz] to [/tmp]
2018-09-06T13:19:44.79+0800 [STG/0] OUT Downloaded [file:///tmp/buildpacks/259d00c2a434b633814fb18cddc73430/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php7-7.2.8-linux-x64-cflinuxfs2-570d0ad4.tgz] to [/tmp]
2018-09-06T13:19:46.49+0800 [STG/0] OUT Downloaded [file:///tmp/buildpacks/259d00c2a434b633814fb18cddc73430/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer-1.6.5-67bebe9d.phar] to [/tmp]
2018-09-06T13:19:49.35+0800 [STG/0] ERR Loading composer repositories with package information
2018-09-06T13:19:49.36+0800 [STG/0] ERR Installing dependencies from lock file
2018-09-06T13:19:49.36+0800 [STG/0] ERR Your requirements could not be resolved to an installable set of packages.
2018-09-06T13:19:49.36+0800 [STG/0] ERR   Problem 1
2018-09-06T13:19:49.36+0800 [STG/0] ERR     - The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension.
2018-09-06T13:19:49.39+0800 [STG/0] OUT -----> Composer command failed
2018-09-06T13:19:49.39+0800 [STG/0] ERR Traceback (most recent call last):
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/scripts/compile.py", line 59, in <module>
2018-09-06T13:19:49.39+0800 [STG/0] ERR     .from_build_pack('lib/additional_commands')
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/lib/build_pack_utils/builder.py", line 209, in extensions
2018-09-06T13:19:49.39+0800 [STG/0] ERR     process_extension(path, ctx, 'compile', process, args=[self])
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/lib/build_pack_utils/utils.py", line 69, in process_extension
2018-09-06T13:19:49.39+0800 [STG/0] ERR     success(getattr(extn, to_call)(*args))
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/extensions/composer/extension.py", line 443, in compile
2018-09-06T13:19:49.39+0800 [STG/0] ERR     return composer.compile(install)
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/lib/extension_helpers.py", line 154, in compile
2018-09-06T13:19:49.39+0800 [STG/0] ERR     self._compile(install)
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/extensions/composer/extension.py", line 196, in _compile
2018-09-06T13:19:49.39+0800 [STG/0] ERR     self.run()
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/extensions/composer/extension.py", line 343, in run
2018-09-06T13:19:49.39+0800 [STG/0] ERR     *self._ctx['COMPOSER_INSTALL_OPTIONS'])
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/extensions/composer/extension.py", line 389, in run
2018-09-06T13:19:49.39+0800 [STG/0] ERR     shell=True)
2018-09-06T13:19:49.39+0800 [STG/0] ERR   File "/tmp/buildpacks/259d00c2a434b633814fb18cddc73430/lib/build_pack_utils/runner.py", line 109, in stream_output
2018-09-06T13:19:49.39+0800 [STG/0] ERR     raise CalledProcessError(retcode, cmd)
2018-09-06T13:19:49.39+0800 [STG/0] ERR build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7fbf519fb9c0>' returned non-zero exit status 2
2018-09-06T13:19:49.40+0800 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 1
2018-09-06T13:19:49.41+0800 [STG/0] OUT Exit status 223
--

Please help to fix this.

Thank you

vanchin

**Comment by vlvanchin** [comment]
The contents of the manifest file is:
$ cat manifest.yml
`
---
applications:
\- name: dbclient-dev
  memory: 512M
  instances: 1
  path: .
  buildpack: php_buildpack
  services:
  \- ThingType Mysql Dev
`

**Comment by vnc-digital** [comment]
When we are pushong laravel code to cloudfoundry. Its throwing same error. Please help me we with this issue
