### ISSUE TITLE
unit testing fails with ImportError on assert_raises_regexp

### ISSUE THREAD

**Issue by jitheshktv** [cloudfoundry/php-buildpack#284]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
>> CF: 1.12.x
>> CLI :  6.34.1

What version of the buildpack you are using?
>> 4.3.66

If you were attempting to accomplish a task, what was it you were attempting to do?
>> perform unit test

What did you expect to happen?
>> Unit test to succeed

What was the actual behavior?
>> Unit test fails with the below error

Running test [./tests/test_compile_helpers.py]...
Failure: ImportError (cannot import name assert_raises_regexp) ... ERROR

======================================================================
ERROR: Failure: ImportError (cannot import name assert_raises_regexp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jt94174/buildpacks/php-buildpack/env/lib/python2.6/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/jt94174/buildpacks/php-buildpack/env/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/jt94174/buildpacks/php-buildpack/env/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/jt94174/buildpacks/php-buildpack/tests/test_compile_helpers.py", line 7, in <module>
    from nose.tools import assert_raises_regexp
ImportError: cannot import name assert_raises_regexp

----------------------------------------------------------------------

The below steps required for the unit tests were performed

git clone https://github.com/cloudfoundry/php-buildpack
cd php-buildpack
python -V  ( the version is reported as 2.6.6)
virtualenv `pwd`/env
. ./env/bin/activate
pip install -r requirements.txt

Please help with this.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by kardolus** [comment]
Following the setup instructions [here](https://github.com/cloudfoundry/php-buildpack#setup) fails for me as well- but with a different error. Perhaps it's time for us to update the README a bit. Will discuss with the team.

**Comment by kardolus** [comment]
Closing due to inactivity - we are about to setup cnb documentation (on cloud foundry). And will make sure the readme of the php cnbs is up to date. 

Feel free to reopen
