### ISSUE TITLE
Fails "php artisan up" : Call to undefined function splitStringByWidth

### ISSUE THREAD

**Issue by syui** [cloudfoundry/php-buildpack#295]
`$ php artisan up` fails.

```sh
$ bx cf ssh $APP_NAME
> cd app
> ./php/bin/php artisan up
Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\mb_detect_encoding() in /home/vcap/app/vendor/symfony/console/Application.php:1121
Stack trace:
#0 /home/vcap/app/vendor/symfony/console/Application.php(780): Symfony\Component\Console\Application->splitStringByWidth('Call to undefin...', 145)
#1 /home/vcap/app/vendor/symfony/console/Application.php(750): Symfony\Component\Console\Application->doRenderException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/vcap/app/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(134): Symfony\Component\Console\Application->renderException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(365): GrahamCampbell\Exceptions\ExceptionHandler->renderForConsole(Object(Symfony\Component\Console\Output\ConsoleOutput), Obje in /home/vcap/app/vendor/symfony/console/Application.php on line 1121

$ vi /home/vcap/app/vendor/symfony/console/Application.php
private function splitStringByWidth($string, $width)
    {
        // str_split is not suitable for multi-byte characters, we should use preg_split to get char array properly.
        // additionally, array_slice() is not enough as some character has doubled width.
        // we need a function to split string not by character count but by string width
        if (false === $encoding = mb_detect_encoding($string, null, true)) {
            return str_split($string, $width);
        }
```

https://github.com/cloudfoundry/php-buildpack/issues/293 , https://github.com/cloudfoundry/php-buildpack/issues/294

**Comment by syui** [comment]
```sh
start command : $HOME/.bp/bin/start

$ cf logs cachet --recent
failed MSpanList_Insert 0xf54000 0x47bfbf1f537 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x987e60, 0x10)
        /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbfe200 sp=0x7ffeefbfe1e8
runtime.(*mSpanList).insert(0xe18dc8, 0xf54000)
        /usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbfe230 sp=0x7ffeefbfe200
runtime.(*mheap).freeSpanLocked(0xe185c0, 0xf54000, 0x100, 0x0)
        /usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbfe298 sp=0x7ffeefbfe230
runtime.(*mheap).grow(0xe185c0, 0x8, 0x0)
        /usr/local/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbfe2f0 sp=0x7ffeefbfe298
runtime.(*mheap).allocSpanLocked(0xe185c0, 0x1, 0x0)
        /usr/local/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbfe348 sp=0x7ffeefbfe2f0
runtime.(*mheap).alloc_m(0xe185c0, 0x1, 0x15, 0x0)
        /usr/local/go/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbfe378 sp=0x7ffeefbfe348
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbfe3a8 sp=0x7ffeefbfe378
runtime.systemstack(0x7ffeefbfe3c8)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbfe3b0 sp=0x7ffeefbfe3a8
runtime.(*mheap).alloc(0xe185c0, 0x1, 0x10000000015, 0x11b8f)
        /usr/local/go/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbfe3f8 sp=0x7ffeefbfe3b0
runtime.(*mcentral).grow(0xe1a1c0, 0x0)
        /usr/local/go/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbfe460 sp=0x7ffeefbfe3f8
runtime.(*mcentral).cacheSpan(0xe1a1c0, 0xe128c8)
        /usr/local/go/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbfe4a0 sp=0x7ffeefbfe460
runtime.(*mcache).refill(0xf50000, 0x15, 0x7ffeefbfe508)
        /usr/local/go/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbfe4d8 sp=0x7ffeefbfe4a0
runtime.mallocgc.func2()
        /usr/local/go/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbfe4f8 sp=0x7ffeefbfe4d8
runtime.systemstack(0x7ffeefbfe598)
        /usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbfe500 sp=0x7ffeefbfe4f8
runtime.mallocgc(0x180, 0x8f7e80, 0x0, 0x800000000)
        /usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbfe5d8 sp=0x7ffeefbfe500
runtime.newobject(0x8f7e80, 0xe12e10)
        /usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbfe600 sp=0x7ffeefbfe5d8
runtime.malg(0x8000, 0xe131c0)
        /usr/local/go/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbfe638 sp=0x7ffeefbfe600
runtime.mpreinit(0xe13980)
        /usr/local/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbfe650 sp=0x7ffeefbfe638
runtime.mcommoninit(0xe13980)
        /usr/local/go/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbfe698 sp=0x7ffeefbfe650
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbfe6e0 sp=0x7ffeefbfe698
runtime.rt0_go(0x7ffeefbfe710, 0x4, 0x7ffeefbfe710, 0x0, 0x4, 0x7ffeefbfec68, 0x7ffeefbfec6b, 0x7ffeefbfec70, 0x7ffeefbfec77, 0x0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbfe6e8 sp=0x7ffeefbfe6e0

```

**Comment by dmikusa-pivotal** [comment]
In regards to this...

```
$ bx cf ssh $APP_NAME
> cd app
> ./php/bin/php artisan up
```

I would suggest that you source all the env variables first. If the environment is not set up properly, you might see some weirdness. After you `cf ssh` into your app, run `source app/.profile.d/finalize_bp_env_vars.sh`. After that, you should be able to run `php -v` or `php -m` and a.) `php` should be on the path and b.) `php` should list all your loaded extensions.

**Comment by dmikusa-pivotal** [comment]
In regards to this...

```
$ cf logs $APP_NAME --recent
failed MSpanList_Insert 0xf54000 0x47bfbf1f537 0x0 0x0
fatal error: MSpanList_Insert
```

That is a golang stack trace, which indicates a problem with your cli. Try getting the most up-to-date version or contact IBM Support, since you're using `bx`.

**Comment by syui** [comment]
Thank you very much for your quick reply.

**Comment by syui** [comment]
I tried to execute with "bx and cf command".

PATH is exported, But php can not run without PATH.

The probable cause is that $HOME is "/home", php is under `/home/app` .

Maybe there is a discrepancy between $ HOME in manifest.yml and ssh (bash)?

- manifest.yml : $HOME = /home/app

- bash (ssh) : $HOME = /home

```sh
$ cf ssh $APP_NAME
$ source app/.profile.d/finalize_bp_env_vars.sh
$ php -v
bash: php: command not found
$ echo $PATH
/bin:/usr/bin:/home/vcap/php/bin:/home/vcap/php/sbin:/home/vcap/php/bin:/home/vcap/php/sbin
v

$ vi .bashrc # diff 
+ export PHPRC=$HOME/app/php/etc
+ export PATH=$PATH:$HOME/app/php/bin:$HOME/app/php/sbin
+ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/app/php/lib
- export PHPRC=$HOME/php/etc
- export PATH=$PATH:$HOME/app/php/bin:$HOME/php/sbin
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/php/lib

$ bash
$ php -v 
PHP 7.1.26 (cli) 
```

**Comment by dmikusa-pivotal** [comment]
Sorry, my fault. You need to run `HOME=/home/vcap/app source app/.profile.d/finalize_bp_env_vars.sh`. CF sets HOME to the app root, but when you `cf ssh` home is the normal user home directory, not the app directory.

**Comment by syui** [comment]
Everything went well. Thank you very much.

**Comment by syui** [comment]
@dmikusa-pivotal 

It seems that "WEBDIR: public" in `.bc-config/option.json` is not enabled ?

I want to set server directory = `/home/vcap/app/public` . 

Do you have any sugesstions?

```sh
$ cf logs $APP_NAME --recent
Attempt to serve directory: /home/vcap/app/htdocs/
```

**Comment by syui** [comment]
I'm sorry typo, `.bp-config`

**Comment by dmikusa-pivotal** [comment]
OK, definitely make sure you have `.bp-config` it has to be that exactly and make sure it's `options.json`, not `option.json`. It has to be plural.

See this example of how this folder/file should be set up. -> https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin/blob/master/.bp-config/options.json

**Comment by dmikusa-pivotal** [comment]
If that still doesn't work, put together a demo/sample where it's failing and I'll take a look.

**Comment by syui** [comment]
Sorry, it's my mistake, I appreciate you pointing out my mistakes.

**Comment by syui** [comment]
Thank you for helping me with so many things.
