### ISSUE TITLE
PHP Bulid pack failed in compilation phase

### ISSUE THREAD

**Issue by srinivasa09** [cloudfoundry/php-buildpack#338]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**

cf version 6.49.0+d0dfa93bb.2020-01-07

**What version of the buildpack you are using?**
i am running  below command  So i guess default version
cf push -b https://github.com/cloudfoundry/php-buildpack.git -s cflinuxfs3

**If you were attempting to accomplish a task, what was it you were attempting to do?**
i am trying to push phpgpadmin (https://github.com/cloudfoundry-community/phppgadmin-cf)

**What did you expect to happen?**
Successful start of PHP APP

**What was the actual behavior?**
PHP app Push is failing

Please confirm where necessary:
* [ ] I have included a log output
* [x ] My log includes an error message
* [ ] I have included steps for reproduction

**Error in CF Console** 

```
WARNING: PHP version 5.5.* not available, using default version (7.2.28). In future versions of the buildpack, specifying a non-existent PHP version will cause staging to fail. See: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-composer.html
   Installing HTTPD
   HTTPD 2.4.41
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd-2.4.41-linux-x64-cflinuxfs3-14955ebb.tgz] to [/tmp]
   Installing PHP
   PHP 7.2.28
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.28-linux-x64-cflinuxfs3-1217a50b.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.28-linux-x64-cflinuxfs3-1217a50b.tgz] to [/tmp]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/composer/composer-1.9.3-e022309c.phar] to [/tmp]
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100   578  100   578    0     0   4099      0 --:--:-- --:--:-- --:--:--  4128

     [Composer\Json\JsonValidationException]
     "./composer.json" does not match the expected JSON schema:
      - type : Does not match the regex pattern ^[a-z0-9-]+$

   -----> Composer command failed
   Traceback (most recent call last):
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/scripts/compile.py", line 59, in <module>
       .from_build_pack('lib/additional_commands')
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/builder.py", line 212, in extensions
       process_extension(path, ctx, 'compile', process, args=[self])
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/utils.py", line 69, in process_extension
       success(getattr(extn, to_call)(*args))
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 444, in compile
       return composer.compile(install)
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/extension_helpers.py", line 154, in compile
       self._compile(install)
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 196, in _compile
       self.run()
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 343, in run
       *self._ctx['COMPOSER_INSTALL_OPTIONS'])
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/extensions/composer/extension.py", line 390, in run
       shell=True)
     File "/tmp/buildpackdownloads/a8097900bb0ea6f0bb97ef3a727783fc/lib/build_pack_utils/runner.py", line 109, in stream_output
       raise CalledProcessError(retcode, cmd)
   build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7f50a7e88930>' returned non-zero exit status 1
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223
   Cell 9a74fbb8-6111-4967-a99e-69d3b560aff8 stopping instance 4a1d3f0c-ae0e-4729-b633-de620c428968
   Cell 9a74fbb8-6111-4967-a99e-69d3b560aff8 destroying container for instance 4a1d3f0c-ae0e-4729-b633-de620c428968
Error staging application: App staging failed in the buildpack compile phase
```

**Comment by dmikusa-pivotal** [comment]
That is an error from Composer. It doesn't like your `composer.json` file. "Application" should be "application". That sample repo is very old, it will probably give you an equally old phpPgAdmin install.

Maybe try -> https://github.com/cloudfoundry-samples/cf-ex-phppgadmin instead. I just updated the instructions and it should give you the most recent phpPgAdmin install.

**Comment by srinivasa09** [comment]
Great thanks for the Solution... this project https://github.com/cloudfoundry-samples/cf-ex-phppgadmin  works like charm

Thanks again..
