### ISSUE TITLE
App with vendor directory, but no composer.json file fails

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#44]
If I try to run an application that contains a vendor directory with vendored dependencies, but without a composer.json file the application will fail to stage.

```
2015-02-17T12:20:56.32+0530 [STG]     OUT Composer could not find a composer.json file in /tmp/staged/app
2015-02-17T12:20:56.33+0530 [STG]     OUT -----> Composer command failed
2015-02-17T12:20:56.33+0530 [STG]     ERR Traceback (most recent call last):
2015-02-17T12:20:56.33+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/scripts/compile.py", line 50, in <module>
2015-02-17T12:20:56.33+0530 [STG]     ERR     .from_build_pack('lib/additional_commands')
2015-02-17T12:20:56.33+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/build_pack_utils/builder.py", line 180, in extensions
2015-02-17T12:20:56.33+0530 [STG]     ERR     process_extension(path, ctx, 'compile', process, args=[self])
2015-02-17T12:20:56.33+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-02-17T12:20:56.33+0530 [STG]     ERR     success(getattr(extn, to_call)(*args))
2015-02-17T12:20:56.33+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/extensions/composer/extension.py", line 356, in compile
2015-02-17T12:20:56.33+0530 [STG]     ERR     return composer.compile(install)
2015-02-17T12:20:56.33+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/extension_helpers.py", line 154, in compile
2015-02-17T12:20:56.34+0530 [STG]     ERR     self.run()
2015-02-17T12:20:56.34+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/extensions/composer/extension.py", line 283, in run
2015-02-17T12:20:56.34+0530 [STG]     ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/build_pack_utils/runner.py", line 109, in stream_output
2015-02-17T12:20:56.34+0530 [STG]     ERR     raise CalledProcessError(retcode, cmd)
2015-02-17T12:20:56.57+0530 [API]     ERR encountered error: App staging failed in the buildpack compile phase
```

It seems like the build pack is incorrectly detecting that Composer needs to be run, probably because it's seeing the composer.json files included by the dependencies.  Right now it's searching the entire app for composer.json files, it might be better to only search the top one or two levels or some key locations.

**Comment by dmikusa-pivotal** [comment]
Pushed a [fix](https://github.com/cloudfoundry/php-buildpack/commit/964aeced36906c126648a093152e4b846636f27f) for this.

**Comment by dmikusa-pivotal** [comment]
I don't think my fix for this goes far enough.  Another [use case](http://support.run.pivotal.io/entries/81291835-cf-deploy-crashing-with-Composer-could-not-find-a-composer-json-file-in-tmp-staged-app) has surfaced where the build pack is incorrectly detecting a composer.json file.

I think we need to review why the build pack is doing a search for the composer.json file and not just looking for it in the root application directory.  It seems like that would be the better approach.

**Comment by jtarchie** [comment]
This issue was resolved with the [commit](https://github.com/cloudfoundry/php-buildpack/commit/5274340f350ce525149ea2e01ec23a82a9b89f51). Please reopen if there are any future issues.
