### ISSUE TITLE
Problems with downloading files

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/php-buildpack#55]
If an app has a custom extension that goes to download files, it fails with this error.

```
o [/tmp/php-mysqli-5.4.39.tar.gz]
2015-03-24T10:54:25.95-0400 [STG/0]      OUT Installing PHPMyAdmin 4.2.11
2015-03-24T10:54:25.95-0400 [STG/0]      ERR Traceback (most recent call last):
2015-03-24T10:54:25.95-0400 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 51, in <module>
2015-03-24T10:54:25.95-0400 [STG/0]      ERR     .from_build_pack('lib/additional_commands')
2015-03-24T10:54:25.95-0400 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 189, in extensions
2015-03-24T10:54:25.95-0400 [STG/0]      ERR     process_extension(path, ctx, 'compile', process, args=[self])
2015-03-24T10:54:25.95-0400 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-03-24T10:54:25.95-0400 [STG/0]      ERR     success(getattr(extn, to_call)(*args))
2015-03-24T10:54:25.95-0400 [STG/0]      ERR   File "/tmp/staged/app/.extensions/phpmyadmin/extension.py", line 47, in compile
2015-03-24T10:54:25.95-0400 [STG/0]      ERR     strip=True)
2015-03-24T10:54:25.95-0400 [STG/0]      ERR TypeError: install_binary_direct() got multiple values for keyword argument 'fileName'
2015-03-24T10:54:25.98-0400 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-03-24T10:54:26.17-0400 [API/7]      ERR encountered error: App staging failed in the buildpack compile phase
```

See this app as an example.

https://github.com/dmikusa-pivotal/cf-ex-phpmyadmin

**Comment by dmikusa-pivotal** [comment]
One workaround is to use a slightly older variation of the build pack.  You can do this with the `-b` argument to `cf push` or with the `buildpack` attribute in your manifest.yml file.

Ex:  `buildpack:  https://github.com/cloudfoundry/php-buildpack#8c13f5434b2f31ca960d2bca9153df1978258535

**Comment by dmikusa-pivotal** [comment]
#56 is a different use case but the same underlying problem.  If a file being downloaded is not in the manifest then you get an error.  It should be possible to download things that are not in the manifest.  The two use cases for this are this ticket, where a user provided build pack extension is trying to download something like app files, and the second is #56 where the build pack is trying to download the absolute latest version of Composer.

**Comment by flavorjones** [comment]
This is now fixed on master. Thanks!

**Comment by dmikusa-pivotal** [comment]
Tested with my PHPMyAdmin example and that is working again.  So is my Wordpress example.

Using Composer with version "latest" is not working though.  It fails with the following error.

```
2015-04-06T11:49:28.02-0400 [STG/0]      ERR 2015-04-06 15:49:28,023 [DEBUG] utils - line #181 in /tmp/buildpacks/cf-php-build-pack/extensions/composer/extension.py, "install" is setting [COMPOSER_DOWNLOAD_URL] = [https://getcomposer.org/composer.phar]
2015-04-06T11:49:28.02-0400 [STG/0]      ERR 2015-04-06 15:49:28,023 [DEBUG] cache - Using hashlib.
2015-04-06T11:49:28.02-0400 [STG/0]      ERR 2015-04-06 15:49:28,024 [INFO] cache - Using [/tmp/cache] as cache directory.
2015-04-06T11:49:28.02-0400 [STG/0]      ERR 2015-04-06 15:49:28,024 [DEBUG] cloudfoundry - Using python downloader.
2015-04-06T11:49:28.02-0400 [STG/0]      ERR 2015-04-06 15:49:28,024 [DEBUG] downloads - Loaded proxy handlers [{}]
2015-04-06T11:49:28.27-0400 [STG/0]      ERR Traceback (most recent call last):
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/scripts/compile.py", line 51, in <module>
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     .from_build_pack('lib/additional_commands')
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/build_pack_utils/builder.py", line 189, in extensions
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     process_extension(path, ctx, 'compile', process, args=[self])
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     success(getattr(extn, to_call)(*args))
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/extensions/composer/extension.py", line 399, in compile
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     return composer.compile(install)
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/extension_helpers.py", line 154, in compile
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     self._compile(install)
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/extensions/composer/extension.py", line 161, in _compile
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/extensions/composer/extension.py", line 186, in install
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     extract=False)
2015-04-06T11:49:28.27-0400 [STG/0]      ERR   File "/tmp/buildpacks/cf-php-build-pack/lib/build_pack_utils/cloudfoundry.py", line 179, in _install_binary_from_manifest
2015-04-06T11:49:28.27-0400 [STG/0]      ERR     print "Could not get translated url, exited with: %s", translate_url_output
2015-04-06T11:49:28.27-0400 [STG/0]      ERR NameError: global name 'translate_url_output' is not defined
2015-04-06T11:49:28.27-0400 [STG/0]      OUT Could not get translated url, exited with: %s
2015-04-06T11:49:28.30-0400 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-04-06T11:49:28.49-0400 [API/9]      ERR encountered error: App staging failed in the buildpack compile phase
```

It also appears like the build pack is no longer caching downloads, but is instead re-downloading resources on every push.  I thought this was a known issue, but mentioning it just in case.

**Comment by flavorjones** [comment]
@dmikusa-pivotal - sorry I'm just getting to this now.

It looks like we solved the originally-reported issue; did you reopen this because of the caching comment (which we know about and will fix); or because of the "composer" "latest" problem? I think if it's either of those two, we should open a new issue. Is that fair?

**Comment by dmikusa-pivotal** [comment]
>because of the "composer" "latest" problem? 

Yes.

>I think if it's either of those two, we should open a new issue. Is that fair?

Sounds good to me.  Would you like me to open the new issue?

**Comment by flavorjones** [comment]
I've got tracker stories for both:

* cache behavior for all buildpacks: https://www.pivotaltracker.com/story/show/92519348
* composer "latest" version support (in "online" mode only, obviously): https://www.pivotaltracker.com/story/show/92519522

Closing this issue.
