### ISSUE TITLE
Error in bluemix?

### ISSUE THREAD

**Issue by ardhipoetra** [cloudfoundry/php-buildpack#57]
Hi guys, 

I'm using this buildpack for my project in ibm bluemix. Several days ago, everything just run fine until today. It seems when bluemix build my project, it asked for github Oauth key. After I provided the key. It keep producing the error like : 
```
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '9f02e38433ca08c2e82cfec8844db9dd26acb336'
-------> Buildpack version 3.1.0

FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

TIP: use 'cf logs locals --recent' for more information
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Thanks!

**Comment by ardhipoetra** [comment]
The error when I didn't provide the github key is like : 
```
-------> Buildpack version 3.1.0
Traceback (most recent call last):
  File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 51, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 223, in done
    process_extension(extn, self._builder._ctx, 'configure', process)
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 66, in process_extension
    extn = load_extension(path)
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 55, in load_extension
    fromlist=['extension'])
  File "/tmp/buildpacks/php-buildpack/extensions/composer/extension.py", line 247
    'Then set COMPOSER_GITHUB_OAUTH_TOKEN in your environment to the value of this token'.)
                                                                                          ^
SyntaxError: invalid syntax
Staging failed: Buildpack compilation step failed

FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase
```

**Comment by dmikusa-pivotal** [comment]
You can work around this by not using master.  You can do this with the -b argument to cf push or with the buildpack attribute in your manifest.yml file.

Ex: `buildpack: https://github.com/cloudfoundry/php-buildpack#5e9e1815544b096f482b6ac717504ea19e63c6c0

**Comment by flavorjones** [comment]
Closing, as this is a bug report against unreleased code.

**Comment by jtarchie** [comment]
An update, the syntax error being experienced was fixed. Apologies for the issue.
