### ISSUE TITLE
failed with github online buildpack 

### ISSUE THREAD

**Issue by flyingoncloud** [cloudfoundry/php-buildpack#63]
I tried to use github online buildpack with different tag like https://github.com/cloudfoundry/php-buildpack#v3.0.4 and failed to push application. 

```
ubuntu@ubuntu14:/mnt/git/cf-acceptance-tests/assets/php$ cat  manifest.yml
---
applications:
- name: php
  memory: 128M
  instances: 1
  env:
    BP_DEBUG: true
ubuntu@ubuntu14:/mnt/git/cf-acceptance-tests/assets/php$


ubuntu@ubuntu14:/mnt/git/cf-acceptance-tests/assets/php$ cf push -b https://github.com/cloudfoundry/php-buildpack#v3.0.4
Using manifest file /mnt/git/cf-acceptance-tests/assets/php/manifest.yml


Creating app php in org apps / space dev as admin...
OK

Using route php.xxxxxx.io
Binding php.xxxxxx.io to php...
OK

Uploading php...
Uploading app files from: /mnt/git/cf-acceptance-tests/assets/php
Uploading 165, 1 files

                             
Done uploading
OK

Starting app php in org apps / space dev as admin...
-----> Downloaded app package (4.0K)
Cloning into '/tmp/buildpacks/php-buildpack'...

FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

TIP: use 'cf logs php --recent' for more information



ubuntu@ubuntu14:/mnt/git/cf-acceptance-tests/assets/php$ cf logs php --recent
Connected, dumping recent logs for app php in org apps / space dev as admin...

2015-04-09T00:27:17.56+0000 [STG/0]      ERR 2015-04-09 00:27:17,568 [DEBUG] utils - line #34 in /tmp/buildpacks/php-buildpack/lib/php/extension.py, "_configure" is setting [ALL_PHP_EXTENSIONS] = [defaultdict(<type 'list'>, {u'5.5.20': [u'amqp', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xcache', u'xdebug', u'xhprof', u'zip', u'zlib'], u'5.5.21': [u'amqp', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'lua', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xcache', u'xdebug', u'xhprof', u'xsl', u'yaf', u'zip', u'zlib'], u'5.5.19': [u'amqp', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xcache', u'xdebug', u'xhprof', u'zip', u'zlib'], u'5.6.4': [u'amqp', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xdebug', u'zip', u'zlib'], u'5.6.5': [u'amqp', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'lua', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xdebug', u'xsl', u'yaf', u'zip', u'zlib'], u'5.4.35': [u'amqp', u'apc', u'apcu', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xcache', u'xdebug', u'xhprof', u'zip', u'zlib'], u'5.4.36': [u'amqp', u'apc', u'apcu', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xcache', u'xdebug', u'xhprof', u'zip', u'zlib'], u'5.4.37': [u'amqp', u'apc', u'apcu', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'lua', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xcache', u'xdebug', u'xhprof', u'xsl', u'yaf', u'zip', u'zlib', u'zookeeper'], u'5.6.3': [u'amqp', u'bz2', u'curl', u'dba', u'exif', u'fileinfo', u'ftp', u'gd', u'gettext', u'gmp', u'igbinary', u'imagick', u'imap', u'intl', u'ioncube', u'ldap', u'mailparse', u'mbstring', u'mcrypt', u'memcache', u'memcached', u'mongo', u'msgpack', u'mysql', u'mysqli', u'opcache', u'openssl', u'pdo', u'pdo_mysql', u'pdo_pgsql', u'pdo_sqlite', u'pgsql', u'phalcon', u'phpiredis', u'pspell', u'redis', u'snmp', u'soap', u'sockets', u'suhosin', u'sundown', u'twig', u'xdebug', u'zip', u'zlib']})]
2015-04-09T00:27:17.58+0000 [STG/0]      ERR 2015-04-09 00:27:17,581 [DEBUG] utils - Processing extension from [/tmp/buildpacks/php-buildpack/extensions/newrelic] with method [configure]
2015-04-09T00:27:17.58+0000 [STG/0]      ERR 2015-04-09 00:27:17,582 [DEBUG] utils - Loading extension from [/tmp/buildpacks/php-buildpack/extensions/newrelic]
2015-04-09T00:27:17.58+0000 [STG/0]      ERR 2015-04-09 00:27:17,588 [DEBUG] utils - Processing extension from [/tmp/buildpacks/php-buildpack/extensions/composer] with method [configure]
2015-04-09T00:27:17.59+0000 [STG/0]      ERR 2015-04-09 00:27:17,590 [DEBUG] utils - Loading extension from [/tmp/buildpacks/php-buildpack/extensions/composer]
2015-04-09T00:27:17.59+0000 [STG/0]      ERR 2015-04-09 00:27:17,597 [DEBUG] utils - Processing extension from [/tmp/buildpacks/php-buildpack/lib/additional_commands] with method [configure]
2015-04-09T00:27:17.59+0000 [STG/0]      ERR 2015-04-09 00:27:17,599 [DEBUG] utils - Loading extension from [/tmp/buildpacks/php-buildpack/lib/additional_commands]
2015-04-09T00:27:17.60+0000 [STG/0]      ERR 2015-04-09 00:27:17,602 [DEBUG] cache - Using hashlib.
2015-04-09T00:27:17.60+0000 [STG/0]      ERR 2015-04-09 00:27:17,603 [INFO] cache - Using [/tmp/cache] as cache directory.
2015-04-09T00:27:17.60+0000 [STG/0]      ERR 2015-04-09 00:27:17,605 [DEBUG] cloudfoundry - Using python downloader.
2015-04-09T00:27:17.60+0000 [STG/0]      ERR 2015-04-09 00:27:17,607 [DEBUG] downloads - Loaded proxy handlers [{'http': '', 'https': '', 'no': ''}]
2015-04-09T00:27:17.60+0000 [STG/0]      ERR 2015-04-09 00:27:17,609 [INFO] builder - Installed build pack utils.
2015-04-09T00:27:17.61+0000 [STG/0]      ERR 2015-04-09 00:27:17,611 [DEBUG] builder - Copying files from [/tmp/buildpacks/php-buildpack/lib/build_pack_utils] to [/tmp/staged/app/.bp/lib/build_pack_utils]
2015-04-09T00:27:17.61+0000 [STG/0]      ERR 2015-04-09 00:27:17,613 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cache.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/cache.pyc]
2015-04-09T00:27:17.61+0000 [STG/0]      ERR 2015-04-09 00:27:17,616 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/cloudfoundry.pyc]
2015-04-09T00:27:17.61+0000 [STG/0]      ERR 2015-04-09 00:27:17,616 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/runner.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/runner.pyc]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,620 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/process.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/process.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,620 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/runner.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/runner.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,621 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/detecter.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/detecter.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,624 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/hashes.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/hashes.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,625 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cache.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/cache.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,626 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/builder.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,628 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/utils.py]
2015-04-09T00:27:17.62+0000 [STG/0]      ERR 2015-04-09 00:27:17,629 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/zips.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/zips.pyc]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,630 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/downloads.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/downloads.py]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,634 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/__init__.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/__init__.py]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,635 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/detecter.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/detecter.pyc]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,636 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/process.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/process.pyc]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,636 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/zips.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/zips.py]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,638 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/builder.pyc]
2015-04-09T00:27:17.63+0000 [STG/0]      ERR 2015-04-09 00:27:17,639 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.py] to [/tmp/staged/app/.bp/lib/build_pack_utils/cloudfoundry.py]
2015-04-09T00:27:17.64+0000 [STG/0]      ERR 2015-04-09 00:27:17,642 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/hashes.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/hashes.pyc]
2015-04-09T00:27:17.64+0000 [STG/0]      ERR 2015-04-09 00:27:17,643 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/downloads.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/downloads.pyc]
2015-04-09T00:27:17.64+0000 [STG/0]      ERR 2015-04-09 00:27:17,644 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/__init__.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/__init__.pyc]
2015-04-09T00:27:17.64+0000 [STG/0]      ERR 2015-04-09 00:27:17,646 [DEBUG] builder - Copying [/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.pyc] to [/tmp/staged/app/.bp/lib/build_pack_utils/utils.pyc]
2015-04-09T00:27:17.64+0000 [STG/0]      ERR 2015-04-09 00:27:17,647 [DEBUG] utils - Processing extension from [/tmp/buildpacks/php-buildpack/lib/httpd] with method [compile]
2015-04-09T00:27:17.64+0000 [STG/0]      ERR 2015-04-09 00:27:17,649 [DEBUG] utils - Loading extension from [/tmp/buildpacks/php-buildpack/lib/httpd]
2015-04-09T00:27:17.64+0000 [STG/0]      OUT Installing HTTPD
2015-04-09T00:27:17.65+0000 [STG/0]      ERR 2015-04-09 00:27:17,654 [DEBUG] utils - line #41 in /tmp/buildpacks/php-buildpack/lib/httpd/extension.py, "compile" is setting [PHP_FPM_LISTEN] = [127.0.0.1:9000]
2015-04-09T00:27:17.65+0000 [STG/0]      ERR 2015-04-09 00:27:17,655 [DEBUG] cloudfoundry - Installing [HTTPD]
2015-04-09T00:27:17.65+0000 [STG/0]      ERR 2015-04-09 00:27:17,655 [DEBUG] cloudfoundry - Installing direct [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/httpd/2.4.10/httpd-2.4.10.tar.gz]
2015-04-09T00:27:17.66+0000 [STG/0]      ERR 2015-04-09 00:27:17,657 [ERROR] utils - Error with extension [/tmp/buildpacks/php-buildpack/lib/httpd]
2015-04-09T00:27:17.66+0000 [STG/0]      ERR Traceback (most recent call last):
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     success(getattr(extn, to_call)(*args))
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/httpd/extension.py", line 43, in compile
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     .package('HTTPD')
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 156, in package
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     self._installer.install_binary(key)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.py", line 173, in install_binary
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     strip=strip)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.py", line 139, in install_binary_direct
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     digest = self._dwn.download_direct(hsh)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/downloads.py", line 38, in download_direct
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     buf = urllib2.urlopen(url).read()
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     return _opener.open(url, data, timeout)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 391, in open
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     response = self._open(req, data)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 409, in _open
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     '_open', req)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     result = func(*args)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 1180, in https_open
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     return self.do_open(httplib.HTTPSConnection, req)
2015-04-09T00:27:17.66+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 1116, in do_open
2015-04-09T00:27:17.66+0000 [STG/0]      ERR     raise URLError('no host given')
2015-04-09T00:27:17.66+0000 [STG/0]      ERR URLError: <urlopen error no host given>
2015-04-09T00:27:17.67+0000 [STG/0]      ERR Traceback (most recent call last):
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 50, in <module>
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     .from_build_pack('lib/additional_commands')
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 180, in extensions
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     process_extension(path, ctx, 'compile', process, args=[self])
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     success(getattr(extn, to_call)(*args))
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/httpd/extension.py", line 43, in compile
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     .package('HTTPD')
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 156, in package
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     self._installer.install_binary(key)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.py", line 173, in install_binary
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     strip=strip)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.py", line 139, in install_binary_direct
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     digest = self._dwn.download_direct(hsh)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/downloads.py", line 38, in download_direct
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     buf = urllib2.urlopen(url).read()
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     return _opener.open(url, data, timeout)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 391, in open
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     response = self._open(req, data)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 409, in _open
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     '_open', req)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     result = func(*args)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 1180, in https_open
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     return self.do_open(httplib.HTTPSConnection, req)
2015-04-09T00:27:17.67+0000 [STG/0]      ERR   File "/usr/lib/python2.6/urllib2.py", line 1116, in do_open
2015-04-09T00:27:17.67+0000 [STG/0]      ERR     raise URLError('no host given')
2015-04-09T00:27:17.67+0000 [STG/0]      ERR urllib2.URLError: <urlopen error no host given>
2015-04-09T00:27:17.71+0000 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-04-09T00:27:17.92+0000 [API/0]      ERR Encountered error: App staging failed in the buildpack compile phase
ubuntu@ubuntu14:/mnt/git/cf-acceptance-tests/assets/php$ 
```

**Comment by dmikusa-pivotal** [comment]
I've tried to reproduce this and can't.  Here are the steps I took.

1.) I looked at the PHP acceptance-test [here](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/php), which is just one simple index.php file.
2.) I created an empty directory with an index.php file and manifest.yml file.  I populated the manifest.yml file with the information you provided above.
3.) I targeted PWS.
4.) I ran the cf push command you listed above.
5.) The push went OK and the app was deployed.

To debug this further, the following would help.

1.) A complete debug log from the build pack.  The one you included above is cut off at the top.
2.) A sample app that we can use to replicate the problem.
3.) Any information about your environment which might be unique, like if you're behind a proxy, what system your targeting, what version of CF you have deployed, etc...

Thanks

**Comment by flavorjones** [comment]
@flyingoncloud, can you provide us with the information the @dmikusa-pivotal has asked about? I'll leave this open for another day or so, but then I'll close it unless we've heard back.

Thanks so much for reporting your issue, and thanks for using Cloud Foundry.

**Comment by flavorjones** [comment]
I'm going to close this, pending further help from @flyingoncloud to reproduce it. Please feel free to update this story if you'd like the investigation to be continued.
