### ISSUE TITLE
Build Pack Compile phase Error 

### ISSUE THREAD

**Issue by Oliyavanjb** [cloudfoundry/php-buildpack#80]
I am new to CloudFoundry, downloaded the code from git hub php-buildpack and create the same directory structure in our local stash repo and try to point to STASH Repo instead of GitHub, While trying to push the code in command line we are getting the below error.
Could you please help on this.

```
2015-06-22T06:36:21.37-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-zip-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:30.31-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-fpm-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:31.91-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-mysqli-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:33.12-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-zlib-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:34.13-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-pdo_sqlite-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:35.24-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-openssl-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:36.76-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-soap-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:37.87-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-pdo-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:38.92-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-memcache-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:41.02-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-mbstring-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:42.12-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-mysql-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:43.22-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-mcrypt-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:44.53-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-fileinfo-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:45.69-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-curl-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:46.59-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-xsl-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:52.81-0400 [API]     ERR Encountered error: App staging failed in the buildpack compile phase
2015-06-22T06:36:55.81-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.6.7/php-cli-5.6.7.tar.gz] to [/tmp]
2015-06-22T06:36:58.15-0400 [STG]     OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/composer/1.0.0-alpha10/composer.phar] to [/tmp]
2015-06-22T06:36:59.02-0400 [STG]     OUT PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
2015-06-22T06:36:59.26-0400 [STG]     ERR   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2015-06-22T06:36:59.26-0400 [STG]     ERR                                  Dload  Upload   Total   Spent    Left  Speed
2015-06-22T06:36:59.60-0400 [STG]     ERR   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2015-06-22T06:36:59.60-0400 [STG]     ERR 141   283  141   283    0     0    497      0 --:--:-- --:--:-- --:--:--   825
2015-06-22T06:36:59.61-0400 [STG]     ERR /tmp/staged/app/php/bin/php: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
2015-06-22T06:36:59.61-0400 [STG]     ERR Traceback (most recent call last):
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/scripts/compile.py", line 51, in <module>
2015-06-22T06:36:59.61-0400 [STG]     OUT -----> Composer command failed
2015-06-22T06:36:59.61-0400 [STG]     ERR     .from_build_pack('lib/additional_commands')
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/lib/build_pack_utils/builder.py", line 189, in extensions
2015-06-22T06:36:59.61-0400 [STG]     ERR     process_extension(path, ctx, 'compile', process, args=[self])
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-06-22T06:36:59.61-0400 [STG]     ERR     success(getattr(extn, to_call)(*args))
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/extensions/composer/extension.py", line 420, in compile
2015-06-22T06:36:59.61-0400 [STG]     ERR     return composer.compile(install)
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/lib/extension_helpers.py", line 154, in compile
2015-06-22T06:36:59.61-0400 [STG]     ERR     self._compile(install)
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/extensions/composer/extension.py", line 173, in _compile
2015-06-22T06:36:59.61-0400 [STG]     ERR     self.run()
2015-06-22T06:36:59.61-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/extensions/composer/extension.py", line 305, in run
2015-06-22T06:36:59.62-0400 [STG]     ERR     *self._ctx['COMPOSER_INSTALL_OPTIONS'])
2015-06-22T06:36:59.62-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/extensions/composer/extension.py", line 350, in run
2015-06-22T06:36:59.62-0400 [STG]     ERR     shell=True)
2015-06-22T06:36:59.62-0400 [STG]     ERR   File "/tmp/buildpacks/bpackphp/lib/build_pack_utils/runner.py", line 109, in stream_output
2015-06-22T06:36:59.62-0400 [STG]     ERR     raise CalledProcessError(retcode, cmd)
2015-06-22T06:36:59.62-0400 [STG]     ERR build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x28b1db0>' returned non-zero exit status 127
2015-06-22T06:36:59.64-0400 [STG]     OUT Staging failed: Buildpack compilation step failed
```

Thanks in Advance.

**Comment by Oliyavanjb** [comment]
Any Workaround for this issue..

**Comment by mhoran** [comment]
Hey @Oliyavanjb. It looks like you're trying to use the buildpack on an unsupported stack. The master branch only supports the lucid64 and cflinuxfs2 stacks. Perhaps you've configured a custom stack, and removed some of the dependencies?

**Comment by Oliyavanjb** [comment]
@mhoran if i point my build pack source to github php-buildpacke everything looks fine, but i clone latest code from github, and trying to use the my local STASH repo instead of github only i am getting error, i didnt change anything in the code level in the build pack.
I the same error @cf-gitbot also getting and also raised the issue to pivotal.
anyway thank for you input.

**Comment by Oliyavanjb** [comment]
@mhoran if i point my build pack source to github php-buildpacke everything looks fine, but i clone latest code from github, and trying to use the my local STASH repo instead of github only i am getting error, i didnt change anything in the code level in the build pack.
I the same error @cf-gitbot also getting and also raised the issue to pivotal.
anyway thank for you input.

**Comment by jtarchie** [comment]
@Oliyavanjb, @mhoran and I are developers on the buildpacks team at Cloud Foundry. We'd like to help with your issue, but we'd need more information.

* Can you provide what version of CF are you deploying to?
* Please clarify what a STASH repo contains and where its location is. If it is a git repo on your local file system that you are referencing with `cf push -b file://` this is an unsupported feature. The `cf push -b` should always point to a HTTP protocol.
* Are you uploading a packaged version of the buildpack using these [instructions](https://github.com/cloudfoundry/php-buildpack#building)?

And for clarification @cf-gitbot is an automated bot that we have on all our git issues. It notifies us that a new issue has been created on Github.

Kind Regards,

@jtarchie

**Comment by flavorjones** [comment]
Closing, pending response from OP.
